ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_UK_ID UNIQUE 
(
  USERNAME 
, SSN 
, EMAIL 
, BANK_ACCOUNT 
)
USING INDEX 
(
    CREATE UNIQUE INDEX EMPLOYEE_UK ON EMPLOYEE (USERNAME ASC, SSN ASC, EMAIL ASC, BANK_ACCOUNT ASC) 
)
 ENABLE;
