--------------------------------------------------------
--  File created - Thursday-April-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ACCOUNT" 
   (	"EMAIL" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"SURPLUS" NUMBER(8,0), 
	"OWNER_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ACCOUNT"."SURPLUS" IS 'so du tai khoan';
--------------------------------------------------------
--  DDL for Table ASSISTANT
--------------------------------------------------------

  CREATE TABLE "ASSISTANT" 
   (	"ID" NUMBER(15,0), 
	"TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS
--------------------------------------------------------

  CREATE TABLE "BUS" 
   (	"ID" NUMBER(6,0), 
	"BUS_TYPE_ID" NUMBER(3,0), 
	"REGISTRATION" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(10,5), 
	"STATUS" NVARCHAR2(20), 
	"MILES" NUMBER(10,4), 
	"BUY_DATE" DATE, 
	"WARRANTY_MONTH" NUMBER(2,0), 
	"WARRANTY_MILES" NUMBER(6,0), 
	"DESCRIPTION" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "BUS"."REGISTRATION" IS 'số đăng ký xe';
 
   COMMENT ON COLUMN "BUS"."STATUS" IS 'mới, cũ, tốt, ...';
 
   COMMENT ON COLUMN "BUS"."MILES" IS 'số dặm đã chaỵ, cập nhật theo lịch hẹn, không cần real-time';
 
   COMMENT ON COLUMN "BUS"."WARRANTY_MONTH" IS 'số tháng tối đa cho bảo hành, eg. 18 month';
 
   COMMENT ON COLUMN "BUS"."WARRANTY_MILES" IS 'số dặm tối đa cho bảo hành, eg. 150000 km';
 
   COMMENT ON COLUMN "BUS"."DESCRIPTION" IS 'eg. linh kiện thiếu sót';
--------------------------------------------------------
--  DDL for Table BUS_STATION
--------------------------------------------------------

  CREATE TABLE "BUS_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ESTABLISH_DATE" DATE, 
	"OWNER_NAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS_TYPE
--------------------------------------------------------

  CREATE TABLE "BUS_TYPE" 
   (	"ID" NUMBER(3,0), 
	"BRAND" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"SEATS" NUMBER(3,0), 
	"SPEED" NUMBER(3,2), 
	"CAPACITY_FUEL" NUMBER(6,2), 
	"MASS_NO_LOAD" NUMBER(6,2), 
	"MASS_ALL" NUMBER(6,2), 
	"HEIGHT" NUMBER(6,2), 
	"WIDTH" NUMBER(6,2), 
	"LENGTH" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "BUS_TYPE"."BRAND" IS 'eg. THAO, AERO EXPRESS, MOBIHOME';
 
   COMMENT ON COLUMN "BUS_TYPE"."MODEL" IS 'eg. version, year, ...';
 
   COMMENT ON COLUMN "BUS_TYPE"."SEATS" IS 'eg. 80, 60, 40, 41, 43';
 
   COMMENT ON COLUMN "BUS_TYPE"."SPEED" IS 'eg. 95 km/h';
 
   COMMENT ON COLUMN "BUS_TYPE"."CAPACITY_FUEL" IS 'eg. 240 l';
 
   COMMENT ON COLUMN "BUS_TYPE"."MASS_NO_LOAD" IS 'eg. 10500 kg';
 
   COMMENT ON COLUMN "BUS_TYPE"."MASS_ALL" IS 'eg. 15700 kg';
 
   COMMENT ON COLUMN "BUS_TYPE"."HEIGHT" IS 'unit: m';
 
   COMMENT ON COLUMN "BUS_TYPE"."WIDTH" IS 'unit: m';
 
   COMMENT ON COLUMN "BUS_TYPE"."LENGTH" IS 'unit: m';
--------------------------------------------------------
--  DDL for Table CHARGE_STATION
--------------------------------------------------------

  CREATE TABLE "CHARGE_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ESTABLISH_DATE" DATE, 
	"OWNER_NAME" NVARCHAR2(50), 
	"DATE_APPLY" DATE, 
	"DATE_END" DATE, 
	"FEE_PER_BUS" NUMBER(10,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "CITY" 
   (	"ID" NUMBER(3,0), 
	"NAME" NVARCHAR2(20), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"TEL_CODE" NUMBER(4,0), 
	"ZIP_CODE" NUMBER(7,0), 
	"AREA_CODE" NUMBER(3,0), 
	"CENTER_DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(12,0), 
	"FIRST_NAME" NVARCHAR2(20), 
	"LAST_NAME" NVARCHAR2(20), 
	"TEL" VARCHAR2(15 BYTE), 
	"ADDRESS" NVARCHAR2(200), 
	"FEED_BACK" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "DEPARTMENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"MANAGER_ID" NUMBER(15,0), 
	"OFFICE_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "DEPARTMENT"."TYPE" IS 'eg. Research';
 
   COMMENT ON COLUMN "DEPARTMENT"."NAME" IS 'eg. Phòng nghiên cứu';
--------------------------------------------------------
--  DDL for Table DISTRICT
--------------------------------------------------------

  CREATE TABLE "DISTRICT" 
   (	"ID" NUMBER(5,0), 
	"NAME" NVARCHAR2(50), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"CITY_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DRIVER
--------------------------------------------------------

  CREATE TABLE "DRIVER" 
   (	"ID" NUMBER(15,0), 
	"LICENSE_NUMBER" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(15,0), 
	"FIRST_NAME" NVARCHAR2(50), 
	"LAST_NAME" NVARCHAR2(50), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"BANK_ACCOUNT" VARCHAR2(20 BYTE), 
	"PHOTO_URL" VARCHAR2(500 BYTE), 
	"SALARY" NUMBER(8,4), 
	"ADDRESS" NVARCHAR2(200), 
	"JOIN_DATE" DATE, 
	"SUPERVISOR_ID" NUMBER(15,0), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOOD
--------------------------------------------------------

  CREATE TABLE "FOOD" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" NVARCHAR2(50), 
	"PRICE" NUMBER(10,5), 
	"FOR_VEGETARIAN" NUMBER(1,0), 
	"DRINKABLE" NUMBER(1,0), 
	"FOOD_SHOP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOOD_SHOP
--------------------------------------------------------

  CREATE TABLE "FOOD_SHOP" 
   (	"ID" VARCHAR2(10 BYTE), 
	"CAPACITY" NUMBER(4,0), 
	"QUALITY" NUMBER(3,0), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORY_CHARGE
--------------------------------------------------------

  CREATE TABLE "HISTORY_CHARGE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"AMOUNT_OF_MONEY" NUMBER(30,0), 
	"DATE_INIT" DATE, 
	"DATE_UPDATE" DATE, 
	"STATUS" VARCHAR2(30 BYTE), 
	"EMAIL_ACCOUNT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORY_ON_TRIP
--------------------------------------------------------

  CREATE TABLE "HISTORY_ON_TRIP" 
   (	"ID" NUMBER(8,0), 
	"TRIP_ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" NVARCHAR2(200), 
	"FEE" NUMBER(8,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "LOCATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" NVARCHAR2(50), 
	"ADDRESS" NVARCHAR2(200), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"OPEN_TIME" DATE, 
	"CLOSE_TIME" DATE, 
	"TEL" VARCHAR2(15 BYTE), 
	"DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "LOCATION"."LATITUDE" IS '-86 to 86';
 
   COMMENT ON COLUMN "LOCATION"."LONGTITUDE" IS '-180 to 180';
 
   COMMENT ON COLUMN "LOCATION"."OPEN_TIME" IS 'hh:mm';
 
   COMMENT ON COLUMN "LOCATION"."CLOSE_TIME" IS 'hh:mm';
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "MANAGER" 
   (	"ID" NUMBER(15,0), 
	"START_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFICE
--------------------------------------------------------

  CREATE TABLE "OFFICE" 
   (	"ID" NUMBER(3,0), 
	"NAME" NVARCHAR2(20), 
	"ADDRESS" NVARCHAR2(200), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"IS_HEADQUATER" NUMBER(1,0), 
	"DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "PROMOTION" 
   (	"ID" NUMBER(6,0), 
	"NAME" NVARCHAR2(100), 
	"CODE" VARCHAR2(15 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"DESCRIPTION" NVARCHAR2(500), 
	"CUT_PRICE" NUMBER(8,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "PROMOTION_TRIP_DAILY" 
   (	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"PROMOTION_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIR_EVENT
--------------------------------------------------------

  CREATE TABLE "REPAIR_EVENT" 
   (	"ID" NUMBER(6,0), 
	"BUS_ID" NUMBER(8,0), 
	"REPAIR_STATION_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" NVARCHAR2(200), 
	"TIME_APPLY" DATE, 
	"CREATOR_ID" NUMBER(15,0), 
	"DRIVER_ID" NUMBER(15,0), 
	"SPENDING" NUMBER(8,4), 
	"ASSISTANCE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIR_STATION
--------------------------------------------------------

  CREATE TABLE "REPAIR_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"QUALITY" NUMBER(3,0), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "ROUTER_TRIP_DAILY" 
   (	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"ORDER_ON_ROUTER" NUMBER(3,0), 
	"DISTANCE_TO" NUMBER(6,0), 
	"DURATION_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ROUTER_TRIP_DAILY"."DISTANCE_TO" IS 'khoang cach tu dau den location nay';
 
   COMMENT ON COLUMN "ROUTER_TRIP_DAILY"."DURATION_TO" IS 'thoi gian (ms) de den cho nay';
 
   COMMENT ON TABLE "ROUTER_TRIP_DAILY"  IS 'Lộ trình trên chuyến đi';
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "SELLER" 
   (	"ID" NUMBER(15,0), 
	"EXP_TRANSACTION" NUMBER(15,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURCHARGE
--------------------------------------------------------

  CREATE TABLE "SURCHARGE" 
   (	"ID" NUMBER(6,0), 
	"NAME" NVARCHAR2(100), 
	"CODE" VARCHAR2(15 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"DESCRIPTION" NVARCHAR2(500), 
	"INCREASE_FEE" NUMBER(8,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "SURCHARGE_TRIP_DAILY" 
   (	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"SURCHARGE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "TICKET" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(40 BYTE), 
	"TRANSACTION_ID" NUMBER(15,0), 
	"TRIP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TRANSACTION" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"CUSTOMER_ID" NUMBER(15,0), 
	"SELLER_ID" NUMBER(15,0), 
	"ACCOUNT" VARCHAR2(100 BYTE), 
	"TOTAL_PRICE" NUMBER(10,4), 
	"PAYMENT_METHOD" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "TRANSACTION"."PAYMENT_METHOD" IS 'office, online';
 
   COMMENT ON COLUMN "TRANSACTION"."STATUS" IS 'finished, paid, pending, ...';
--------------------------------------------------------
--  DDL for Table TRIP
--------------------------------------------------------

  CREATE TABLE "TRIP" 
   (	"ID" VARCHAR2(40 BYTE), 
	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"DEPART_DATE" DATE, 
	"BUS_ID" NUMBER(5,0), 
	"DRIVER_ID" NUMBER(15,0), 
	"ASSISTANT_ID" NUMBER(15,0), 
	"IS_COMPLETE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "TRIP"."DEPART_DATE" IS 'ngày khởi hành';
 
   COMMENT ON COLUMN "TRIP"."IS_COMPLETE" IS '(1/0) - true/false';
--------------------------------------------------------
--  DDL for Table TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "TRIP_DAILY" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"DEPART_STATION_ID" VARCHAR2(10 BYTE), 
	"ARRIVE_STATION_ID" VARCHAR2(10 BYTE), 
	"DEPART_TIME" DATE, 
	"ARRIVE_TIME" DATE, 
	"DURATION" TIMESTAMP (6), 
	"PRICE" NUMBER(8,4), 
	"DISTANCE" NUMBER(15,0), 
	"HOTLINE" VARCHAR2(15 BYTE), 
	"BUS_TYPE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "TRIP_DAILY"."DEPART_STATION_ID" IS 'trạm khởi hành';
 
   COMMENT ON COLUMN "TRIP_DAILY"."ARRIVE_STATION_ID" IS 'trạm đến';
 
   COMMENT ON COLUMN "TRIP_DAILY"."DEPART_TIME" IS 'gi�? khởi hành';
 
   COMMENT ON COLUMN "TRIP_DAILY"."ARRIVE_TIME" IS 'gi�? đến';
--------------------------------------------------------
--  DDL for Table WARRANTY
--------------------------------------------------------

  CREATE TABLE "WARRANTY" 
   (	"REPAIR_STATION_ID" VARCHAR2(20 BYTE), 
	"BUS_TYPE_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON TABLE "WARRANTY"  IS 'Warranty relation between bus_type with repair station';
--------------------------------------------------------
--  DDL for Table WORKER
--------------------------------------------------------

  CREATE TABLE "WORKER" 
   (	"ID" NUMBER(15,0), 
	"JOB_TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into VERSION1.ACCOUNT
SET DEFINE OFF;
REM INSERTING into VERSION1.ASSISTANT
SET DEFINE OFF;
REM INSERTING into VERSION1.BUS
SET DEFINE OFF;
REM INSERTING into VERSION1.BUS_STATION
SET DEFINE OFF;
REM INSERTING into VERSION1.BUS_TYPE
SET DEFINE OFF;
REM INSERTING into VERSION1.CHARGE_STATION
SET DEFINE OFF;
REM INSERTING into VERSION1.CITY
SET DEFINE OFF;
REM INSERTING into VERSION1.CUSTOMER
SET DEFINE OFF;
REM INSERTING into VERSION1.DEPARTMENT
SET DEFINE OFF;
REM INSERTING into VERSION1.DISTRICT
SET DEFINE OFF;
REM INSERTING into VERSION1.DRIVER
SET DEFINE OFF;
REM INSERTING into VERSION1.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into VERSION1.FOOD
SET DEFINE OFF;
REM INSERTING into VERSION1.FOOD_SHOP
SET DEFINE OFF;
REM INSERTING into VERSION1.HISTORY_CHARGE
SET DEFINE OFF;
REM INSERTING into VERSION1.HISTORY_ON_TRIP
SET DEFINE OFF;
REM INSERTING into VERSION1.LOCATION
SET DEFINE OFF;
REM INSERTING into VERSION1.MANAGER
SET DEFINE OFF;
REM INSERTING into VERSION1.OFFICE
SET DEFINE OFF;
REM INSERTING into VERSION1.PROMOTION
SET DEFINE OFF;
REM INSERTING into VERSION1.PROMOTION_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into VERSION1.REPAIR_EVENT
SET DEFINE OFF;
REM INSERTING into VERSION1.REPAIR_STATION
SET DEFINE OFF;
REM INSERTING into VERSION1.ROUTER_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into VERSION1.SELLER
SET DEFINE OFF;
REM INSERTING into VERSION1.SURCHARGE
SET DEFINE OFF;
REM INSERTING into VERSION1.SURCHARGE_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into VERSION1.TICKET
SET DEFINE OFF;
REM INSERTING into VERSION1.TRANSACTION
SET DEFINE OFF;
REM INSERTING into VERSION1.TRIP
SET DEFINE OFF;
REM INSERTING into VERSION1.TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into VERSION1.WARRANTY
SET DEFINE OFF;
REM INSERTING into VERSION1.WORKER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TRIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRIP_PK" ON "TRIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEPARTMENT_PK" ON "DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRIP_DAILY_PK" ON "TRIP_DAILY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_PK" ON "CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROMOTION_TRIP_DAILY_PK" ON "PROMOTION_TRIP_DAILY" ("TRIP_DAILY_ID", "PROMOTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOCATION_PK" ON "LOCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index WARRANTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WARRANTY_PK" ON "WARRANTY" ("REPAIR_STATION_ID", "BUS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DRIVER_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVER_UK" ON "DRIVER" ("LICENSE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROMOTION_PK" ON "PROMOTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_TYPE_PK" ON "BUS_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISTRICT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISTRICT_PK" ON "DISTRICT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OFFICE_PK" ON "OFFICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_PK" ON "ACCOUNT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "WORKER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORY_ON_TRIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORY_ON_TRIP_PK" ON "HISTORY_ON_TRIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY_PK" ON "CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_SHOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD_SHOP_PK" ON "FOOD_SHOP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER_PK" ON "MANAGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROUTER_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUTER_TRIP_DAILY_PK" ON "ROUTER_TRIP_DAILY" ("LOCATION_ID", "TRIP_DAILY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_PK" ON "BUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACTION_PK" ON "TRANSACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD_PK" ON "FOOD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TICKET_PK" ON "TICKET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENT_PK" ON "REPAIR_EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_STATION_PK" ON "BUS_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SELLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELLER_PK" ON "SELLER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DRIVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVER_PK" ON "DRIVER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPAIR_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPAIR_STATION_PK" ON "REPAIR_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURCHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SURCHARGE_PK" ON "SURCHARGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURCHARGE_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SURCHARGE_TRIP_DAILY_PK" ON "SURCHARGE_TRIP_DAILY" ("TRIP_DAILY_ID", "SURCHARGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_PK" ON "EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSISTANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT_PK" ON "ASSISTANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHARGE_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHARGE_STATION_PK" ON "CHARGE_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORY_CHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORY_CHARGE_PK" ON "HISTORY_CHARGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "FOOD" ADD CONSTRAINT "FOOD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "FOOD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_UK" UNIQUE ("LICENSE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DRIVER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_PK" PRIMARY KEY ("TRIP_DAILY_ID", "PROMOTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PROMOTION_TRIP_DAILY" MODIFY ("PROMOTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROMOTION_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "LOCATION" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LOCATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPAIR_STATION
--------------------------------------------------------

  ALTER TABLE "REPAIR_STATION" ADD CONSTRAINT "REPAIR_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "REPAIR_STATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "ASSISTANT" ADD CONSTRAINT "ASSISTANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASSISTANT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPAIR_EVENT
--------------------------------------------------------

  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CUSTOMER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORY_ON_TRIP
--------------------------------------------------------

  ALTER TABLE "HISTORY_ON_TRIP" ADD CONSTRAINT "HISTORY_ON_TRIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HISTORY_ON_TRIP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_PK" PRIMARY KEY ("LOCATION_ID", "TRIP_DAILY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ROUTER_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROUTER_TRIP_DAILY" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ACCOUNT" MODIFY ("OWNER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKER
--------------------------------------------------------

  ALTER TABLE "WORKER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "WORKER" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EMPLOYEE" MODIFY ("SSN" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP
--------------------------------------------------------

  ALTER TABLE "TRIP" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" ADD CONSTRAINT "DISTRICT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DISTRICT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DISTRICT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "PROMOTION" ADD CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PROMOTION" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROMOTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "TICKET" MODIFY ("TRIP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" ADD CONSTRAINT "SELLER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SELLER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUS_STATION
--------------------------------------------------------

  ALTER TABLE "BUS_STATION" ADD CONSTRAINT "BUS_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "BUS_STATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CITY" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CITY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DEPARTMENT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DEPARTMENT" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "OFFICE" ADD CONSTRAINT "OFFICE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "OFFICE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OFFICE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURCHARGE
--------------------------------------------------------

  ALTER TABLE "SURCHARGE" ADD CONSTRAINT "SURCHARGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SURCHARGE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SURCHARGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "TRIP_DAILY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHARGE_STATION
--------------------------------------------------------

  ALTER TABLE "CHARGE_STATION" ADD CONSTRAINT "CHARGE_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CHARGE_STATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOOD_SHOP
--------------------------------------------------------

  ALTER TABLE "FOOD_SHOP" ADD CONSTRAINT "FOOD_SHOP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "FOOD_SHOP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "BUS" ADD CONSTRAINT "BUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "BUS" MODIFY ("REGISTRATION" NOT NULL ENABLE);
 
  ALTER TABLE "BUS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "MANAGER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MANAGER" MODIFY ("START_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WARRANTY
--------------------------------------------------------

  ALTER TABLE "WARRANTY" MODIFY ("BUS_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WARRANTY" MODIFY ("REPAIR_STATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_PK" PRIMARY KEY ("REPAIR_STATION_ID", "BUS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORY_CHARGE
--------------------------------------------------------

  ALTER TABLE "HISTORY_CHARGE" ADD CONSTRAINT "HISTORY_CHARGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HISTORY_CHARGE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HISTORY_CHARGE" MODIFY ("AMOUNT_OF_MONEY" NOT NULL ENABLE);
 
  ALTER TABLE "HISTORY_CHARGE" MODIFY ("DATE_INIT" NOT NULL ENABLE);
 
  ALTER TABLE "HISTORY_CHARGE" MODIFY ("DATE_UPDATE" NOT NULL ENABLE);
 
  ALTER TABLE "HISTORY_CHARGE" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "HISTORY_CHARGE" MODIFY ("EMAIL_ACCOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_PK" PRIMARY KEY ("TRIP_DAILY_ID", "SURCHARGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SURCHARGE_TRIP_DAILY" MODIFY ("SURCHARGE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SURCHARGE_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS_TYPE
--------------------------------------------------------

  ALTER TABLE "BUS_TYPE" ADD CONSTRAINT "BUS_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "BUS_TYPE" MODIFY ("BRAND" NOT NULL ENABLE);
 
  ALTER TABLE "BUS_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK_OWNER" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "ASSISTANT" ADD CONSTRAINT "ASSISTANT_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "BUS" ADD CONSTRAINT "BUS_FK_TYPE" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUS_STATION
--------------------------------------------------------

  ALTER TABLE "BUS_STATION" ADD CONSTRAINT "BUS_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHARGE_STATION
--------------------------------------------------------

  ALTER TABLE "CHARGE_STATION" ADD CONSTRAINT "CHARGE_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CITY" ADD CONSTRAINT "CITY_FK_CENTER" FOREIGN KEY ("CENTER_DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_MANAGER" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "MANAGER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_OFFICE" FOREIGN KEY ("OFFICE_ID")
	  REFERENCES "OFFICE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" ADD CONSTRAINT "DISTRICT_FK_CITY" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CITY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK_DEPART" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK_SUPERVISOR" FOREIGN KEY ("SUPERVISOR_ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "FOOD" ADD CONSTRAINT "FOOD_FK" FOREIGN KEY ("FOOD_SHOP_ID")
	  REFERENCES "FOOD_SHOP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOOD_SHOP
--------------------------------------------------------

  ALTER TABLE "FOOD_SHOP" ADD CONSTRAINT "FOOD_SHOP_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORY_CHARGE
--------------------------------------------------------

  ALTER TABLE "HISTORY_CHARGE" ADD CONSTRAINT "HISTORY_CHARGE_FK1" FOREIGN KEY ("EMAIL_ACCOUNT")
	  REFERENCES "ACCOUNT" ("EMAIL") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORY_ON_TRIP
--------------------------------------------------------

  ALTER TABLE "HISTORY_ON_TRIP" ADD CONSTRAINT "HISTORY_ON_TRIP_FK_TRIP" FOREIGN KEY ("TRIP_ID")
	  REFERENCES "TRIP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "OFFICE" ADD CONSTRAINT "OFFICE_FK_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_FK_PRO" FOREIGN KEY ("PROMOTION_ID")
	  REFERENCES "PROMOTION" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_EVENT
--------------------------------------------------------

  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK1" FOREIGN KEY ("ASSISTANCE_ID")
	  REFERENCES "ASSISTANT" ("ID") ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_BUS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "BUS" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_CREATOR" FOREIGN KEY ("CREATOR_ID")
	  REFERENCES "MANAGER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "DRIVER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_STATION" FOREIGN KEY ("REPAIR_STATION_ID")
	  REFERENCES "REPAIR_STATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_STATION
--------------------------------------------------------

  ALTER TABLE "REPAIR_STATION" ADD CONSTRAINT "REPAIR_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_FK_LOC" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" ADD CONSTRAINT "SELLER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_FK_SUR" FOREIGN KEY ("SURCHARGE_ID")
	  REFERENCES "SURCHARGE" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_FK_TRANSACTION" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANSACTION" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_FK_TRIP" FOREIGN KEY ("TRIP_ID")
	  REFERENCES "TRIP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_ACCOUNT" FOREIGN KEY ("ACCOUNT")
	  REFERENCES "ACCOUNT" ("EMAIL") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_SELLER" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "SELLER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIP
--------------------------------------------------------

  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_ASSISTANT" FOREIGN KEY ("ASSISTANT_ID")
	  REFERENCES "ASSISTANT" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_BUS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "BUS" ("ID") ENABLE;
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_DAILY" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "DRIVER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_AR_ID" FOREIGN KEY ("ARRIVE_STATION_ID")
	  REFERENCES "BUS_STATION" ("ID") ENABLE;
 
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_BUS_TYPE" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_DE_ID" FOREIGN KEY ("DEPART_STATION_ID")
	  REFERENCES "BUS_STATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WARRANTY
--------------------------------------------------------

  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_FK_BUS" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_FK_STATION" FOREIGN KEY ("REPAIR_STATION_ID")
	  REFERENCES "REPAIR_STATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKER
--------------------------------------------------------

  ALTER TABLE "WORKER" ADD CONSTRAINT "WORKER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
