--------------------------------------------------------
--  File created - Tuesday-May-01-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ACCOUNT" 
   (	"EMAIL" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"SURPLUS" NUMBER(8,0), 
	"OWNER_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ACCOUNT"."SURPLUS" IS 'so du tai khoan';
--------------------------------------------------------
--  DDL for Table ASSISTANT
--------------------------------------------------------

  CREATE TABLE "ASSISTANT" 
   (	"ID" NUMBER(15,0), 
	"TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS
--------------------------------------------------------

  CREATE TABLE "BUS" 
   (	"ID" NUMBER(6,0), 
	"BUS_TYPE_ID" NUMBER(3,0), 
	"REGISTRATION" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(15,5), 
	"STATUS" NVARCHAR2(20), 
	"MILES" NUMBER(15,4), 
	"BUY_DATE" DATE, 
	"WARRANTY_MONTH" NUMBER(2,0), 
	"WARRANTY_MILES" NUMBER(6,0), 
	"DESCRIPTION" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "BUS"."REGISTRATION" IS 'số đăng ký xe';
 
   COMMENT ON COLUMN "BUS"."STATUS" IS 'mới, cũ, tốt, ...';
 
   COMMENT ON COLUMN "BUS"."MILES" IS 'số dặm đã chaỵ, cập nhật theo lịch hẹn, không cần real-time';
 
   COMMENT ON COLUMN "BUS"."WARRANTY_MONTH" IS 'số tháng tối đa cho bảo hành, eg. 18 month';
 
   COMMENT ON COLUMN "BUS"."WARRANTY_MILES" IS 'số dặm tối đa cho bảo hành, eg. 150000 km';
 
   COMMENT ON COLUMN "BUS"."DESCRIPTION" IS 'eg. linh kiện thiếu sót';
--------------------------------------------------------
--  DDL for Table BUS_STATION
--------------------------------------------------------

  CREATE TABLE "BUS_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ESTABLISH_DATE" DATE, 
	"OWNER_NAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS_TYPE
--------------------------------------------------------

  CREATE TABLE "BUS_TYPE" 
   (	"ID" NUMBER(3,0), 
	"BRAND" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"SEATS" NUMBER(3,0), 
	"SPEED" NUMBER(7,2), 
	"CAPACITY_FUEL" NUMBER(7,2), 
	"MASS_NO_LOAD" NUMBER(7,2), 
	"MASS_ALL" NUMBER(7,2), 
	"HEIGHT" NUMBER(7,2), 
	"WIDTH" NUMBER(7,2), 
	"LENGTH" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "BUS_TYPE"."BRAND" IS 'eg. THAO, AERO EXPRESS, MOBIHOME';
 
   COMMENT ON COLUMN "BUS_TYPE"."MODEL" IS 'eg. version, year, ...';
 
   COMMENT ON COLUMN "BUS_TYPE"."SEATS" IS 'eg. 80, 60, 40, 41, 43';
 
   COMMENT ON COLUMN "BUS_TYPE"."SPEED" IS 'eg. 95 km/h';
 
   COMMENT ON COLUMN "BUS_TYPE"."CAPACITY_FUEL" IS 'eg. 240 l';
 
   COMMENT ON COLUMN "BUS_TYPE"."MASS_NO_LOAD" IS 'eg. 10500 kg';
 
   COMMENT ON COLUMN "BUS_TYPE"."MASS_ALL" IS 'eg. 15700 kg';
 
   COMMENT ON COLUMN "BUS_TYPE"."HEIGHT" IS 'unit: m';
 
   COMMENT ON COLUMN "BUS_TYPE"."WIDTH" IS 'unit: m';
 
   COMMENT ON COLUMN "BUS_TYPE"."LENGTH" IS 'unit: m';
--------------------------------------------------------
--  DDL for Table CHARGE_STATION
--------------------------------------------------------

  CREATE TABLE "CHARGE_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ESTABLISH_DATE" DATE, 
	"OWNER_NAME" NVARCHAR2(50), 
	"DATE_APPLY" DATE, 
	"DATE_END" DATE, 
	"FEE_PER_BUS" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "CITY" 
   (	"ID" NUMBER(3,0), 
	"NAME" NVARCHAR2(20), 
	"LATITUDE" NUMBER(3,0), 
	"LONGITUDE" NUMBER(3,0), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"TEL_CODE" NUMBER(4,0), 
	"ZIP_CODE" NUMBER(7,0), 
	"AREA_CODE" NUMBER(3,0), 
	"CENTER_DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(12,0), 
	"FIRST_NAME" NVARCHAR2(20), 
	"LAST_NAME" NVARCHAR2(20), 
	"TEL" VARCHAR2(15 BYTE), 
	"ADDRESS" NVARCHAR2(200), 
	"FEED_BACK" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "DEPARTMENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"MANAGER_ID" NUMBER(15,0), 
	"OFFICE_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "DEPARTMENT"."TYPE" IS 'eg. Research';
 
   COMMENT ON COLUMN "DEPARTMENT"."NAME" IS 'eg. Phòng nghiên cứu';
--------------------------------------------------------
--  DDL for Table DISTRICT
--------------------------------------------------------

  CREATE TABLE "DISTRICT" 
   (	"ID" NUMBER(5,0), 
	"NAME" NVARCHAR2(50), 
	"LATITUDE" NUMBER(3,0), 
	"LONGITUDE" NUMBER(3,0), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"CITY_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DRIVER
--------------------------------------------------------

  CREATE TABLE "DRIVER" 
   (	"ID" NUMBER(15,0), 
	"LICENSE_NUMBER" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(15,0), 
	"FIRST_NAME" NVARCHAR2(50), 
	"LAST_NAME" NVARCHAR2(50), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(50 BYTE), 
	"BANK_ACCOUNT" VARCHAR2(20 BYTE), 
	"PHOTO_URL" VARCHAR2(500 BYTE), 
	"SALARY" NUMBER(15,4), 
	"ADDRESS" NVARCHAR2(200), 
	"JOIN_DATE" DATE, 
	"SUPERVISOR_ID" NUMBER(15,0), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "EMPLOYEE"."ROLE" IS 'manager, driver, assistant, worker, seller';
--------------------------------------------------------
--  DDL for Table FOOD
--------------------------------------------------------

  CREATE TABLE "FOOD" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" NVARCHAR2(50), 
	"PRICE" NUMBER(10,5), 
	"FOR_VEGETARIAN" NUMBER(1,0), 
	"DRINKABLE" NUMBER(1,0), 
	"FOOD_SHOP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOOD_SHOP
--------------------------------------------------------

  CREATE TABLE "FOOD_SHOP" 
   (	"ID" VARCHAR2(10 BYTE), 
	"CAPACITY" NUMBER(4,0), 
	"QUALITY" NUMBER(3,0), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORY_ON_TRIP
--------------------------------------------------------

  CREATE TABLE "HISTORY_ON_TRIP" 
   (	"ID" NUMBER(8,0), 
	"TRIP_ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" NVARCHAR2(200), 
	"FEE" NUMBER(15,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "LOCATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" NVARCHAR2(50), 
	"ADDRESS" NVARCHAR2(200), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"OPEN_TIME" DATE, 
	"CLOSE_TIME" DATE, 
	"TEL" VARCHAR2(15 BYTE), 
	"DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "LOCATION"."LATITUDE" IS '-86 to 86';
 
   COMMENT ON COLUMN "LOCATION"."LONGTITUDE" IS '-180 to 180';
 
   COMMENT ON COLUMN "LOCATION"."OPEN_TIME" IS 'hh:mm';
 
   COMMENT ON COLUMN "LOCATION"."CLOSE_TIME" IS 'hh:mm';
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "MANAGER" 
   (	"ID" NUMBER(15,0), 
	"START_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFICE
--------------------------------------------------------

  CREATE TABLE "OFFICE" 
   (	"ID" NUMBER(3,0), 
	"NAME" NVARCHAR2(100), 
	"ADDRESS" NVARCHAR2(200), 
	"IS_HEADQUATER" NUMBER(1,0), 
	"DISTRICT_ID" NUMBER(5,0), 
	"HOTLINE" VARCHAR2(50 BYTE), 
	"LATITUDE" NUMBER(15,5), 
	"LONGITUDE" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "PROMOTION" 
   (	"ID" NUMBER(6,0), 
	"NAME" NVARCHAR2(100), 
	"CODE" VARCHAR2(15 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"DESCRIPTION" NVARCHAR2(500), 
	"CUT_PRICE" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "PROMOTION_TRIP_DAILY" 
   (	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"PROMOTION_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIR_EVENT
--------------------------------------------------------

  CREATE TABLE "REPAIR_EVENT" 
   (	"ID" NUMBER(6,0), 
	"BUS_ID" NUMBER(8,0), 
	"REPAIR_STATION_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" NVARCHAR2(200), 
	"TIME_APPLY" DATE, 
	"CREATOR_ID" NUMBER(15,0), 
	"DRIVER_ID" NUMBER(15,0), 
	"SPENDING" NUMBER(8,4), 
	"ASSISTANCE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIR_STATION
--------------------------------------------------------

  CREATE TABLE "REPAIR_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"QUALITY" NUMBER(3,0), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "ROUTER_TRIP_DAILY" 
   (	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"ORDER_ON_ROUTER" NUMBER(3,0), 
	"DISTANCE_TO" NUMBER(6,0), 
	"DURATION_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ROUTER_TRIP_DAILY"."DISTANCE_TO" IS 'khoang cach tu dau den location nay';
 
   COMMENT ON COLUMN "ROUTER_TRIP_DAILY"."DURATION_TO" IS 'thoi gian (ms) de den cho nay';
 
   COMMENT ON TABLE "ROUTER_TRIP_DAILY"  IS 'Lộ trình trên chuyến đi';
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "SELLER" 
   (	"ID" NUMBER(15,0), 
	"EXP_TRANSACTION" NUMBER(15,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURCHARGE
--------------------------------------------------------

  CREATE TABLE "SURCHARGE" 
   (	"ID" NUMBER(6,0), 
	"NAME" NVARCHAR2(100), 
	"CODE" VARCHAR2(15 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"DESCRIPTION" NVARCHAR2(500), 
	"INCREASE_FEE" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "SURCHARGE_TRIP_DAILY" 
   (	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"SURCHARGE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "TICKET" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(40 BYTE), 
	"TRANSACTION_ID" NUMBER(15,0), 
	"TRIP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TRANSACTION" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"CUSTOMER_ID" NUMBER(15,0), 
	"SELLER_ID" NUMBER(15,0), 
	"ACCOUNT" VARCHAR2(100 BYTE), 
	"TOTAL_PRICE" NUMBER(15,4), 
	"PAYMENT_METHOD" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "TRANSACTION"."PAYMENT_METHOD" IS 'office, online';
 
   COMMENT ON COLUMN "TRANSACTION"."STATUS" IS 'finished, paid, pending, ...';
--------------------------------------------------------
--  DDL for Table TRIP
--------------------------------------------------------

  CREATE TABLE "TRIP" 
   (	"ID" VARCHAR2(40 BYTE), 
	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"DEPART_DATE" DATE, 
	"BUS_ID" NUMBER(5,0), 
	"DRIVER_ID" NUMBER(15,0), 
	"ASSISTANT_ID" NUMBER(15,0), 
	"IS_COMPLETE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "TRIP"."DEPART_DATE" IS 'ngày khởi hành';
 
   COMMENT ON COLUMN "TRIP"."IS_COMPLETE" IS '(1/0) - true/false';
--------------------------------------------------------
--  DDL for Table TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "TRIP_DAILY" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"DEPART_STATION_ID" VARCHAR2(10 BYTE), 
	"ARRIVE_STATION_ID" VARCHAR2(10 BYTE), 
	"DEPART_TIME" DATE, 
	"ARRIVE_TIME" DATE, 
	"DURATION" TIMESTAMP (6), 
	"PRICE" NUMBER(15,4), 
	"DISTANCE" NUMBER(15,0), 
	"HOTLINE" VARCHAR2(15 BYTE), 
	"BUS_TYPE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "TRIP_DAILY"."DEPART_STATION_ID" IS 'trạm khởi hành';
 
   COMMENT ON COLUMN "TRIP_DAILY"."ARRIVE_STATION_ID" IS 'trạm đến';
 
   COMMENT ON COLUMN "TRIP_DAILY"."DEPART_TIME" IS 'gi�? khởi hành';
 
   COMMENT ON COLUMN "TRIP_DAILY"."ARRIVE_TIME" IS 'gi�? đến';
--------------------------------------------------------
--  DDL for Table WARRANTY
--------------------------------------------------------

  CREATE TABLE "WARRANTY" 
   (	"REPAIR_STATION_ID" VARCHAR2(20 BYTE), 
	"BUS_TYPE_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON TABLE "WARRANTY"  IS 'Warranty relation between bus_type with repair station';
--------------------------------------------------------
--  DDL for Table WORKER
--------------------------------------------------------

  CREATE TABLE "WORKER" 
   (	"ID" NUMBER(15,0), 
	"JOB_TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ACCOUNT
SET DEFINE OFF;
REM INSERTING into ASSISTANT
SET DEFINE OFF;
REM INSERTING into BUS
SET DEFINE OFF;
REM INSERTING into BUS_STATION
SET DEFINE OFF;
REM INSERTING into BUS_TYPE
SET DEFINE OFF;
REM INSERTING into CHARGE_STATION
SET DEFINE OFF;
REM INSERTING into CITY
SET DEFINE OFF;
Insert into CITY (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL_CODE,ZIP_CODE,AREA_CODE,CENTER_DISTRICT_ID) values (3,'North Diana',-7,-153,'NorthDiana.com',65,89,12,3);
Insert into CITY (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL_CODE,ZIP_CODE,AREA_CODE,CENTER_DISTRICT_ID) values (1,'West Clarenceport',-16,131,'WestClarenceport.com',44,26,2,1);
Insert into CITY (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL_CODE,ZIP_CODE,AREA_CODE,CENTER_DISTRICT_ID) values (2,'New Alma',-45,-62,'NewAlma.com',48,41,72,2);
Insert into CITY (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL_CODE,ZIP_CODE,AREA_CODE,CENTER_DISTRICT_ID) values (5,'Barbaraberg',-69,-8,'Barbaraberg.com',15,64,27,5);
Insert into CITY (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL_CODE,ZIP_CODE,AREA_CODE,CENTER_DISTRICT_ID) values (4,'New Jesse',-73,-163,'NewJesse.com',63,66,24,4);
REM INSERTING into CUSTOMER
SET DEFINE OFF;
REM INSERTING into DEPARTMENT
SET DEFINE OFF;
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('1','Human Resource','Nhan Su',1,1);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('2','Business','Kinh Doanh',2,1);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('3','Financial','Tai Chinh',3,1);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('4','Shipping','Van Chuyen',4,1);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('5','Equipment','Thiet Bi',5,1);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('6','Human Resource','Nhan Su',6,2);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('7','Business','Kinh Doanh',7,2);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('11','Human Resource','Nhan Su',11,3);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('9','Shipping','Van Chuyen',9,2);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('13','Financial','Tai Chinh',13,3);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('8','Financial','Tai Chinh',8,2);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('12','Business','Kinh Doanh',12,3);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('10','Equipment','Thiet Bi',10,2);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('14','Shipping','Van Chuyen',14,3);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('15','Equipment','Thiet Bi',15,3);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('16','Human Resource','Nhan Su',16,4);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('17','Business','Kinh Doanh',17,4);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('18','Financial','Tai Chinh',18,4);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('19','Shipping','Van Chuyen',19,4);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('23','Financial','Tai Chinh',23,5);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('21','Human Resource','Nhan Su',21,5);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('22','Business','Kinh Doanh',22,5);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('20','Equipment','Thiet Bi',20,4);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('24','Shipping','Van Chuyen',24,5);
Insert into DEPARTMENT (ID,TYPE,NAME,MANAGER_ID,OFFICE_ID) values ('25','Equipment','Thiet Bi',25,5);
REM INSERTING into DISTRICT
SET DEFINE OFF;
Insert into DISTRICT (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL,CITY_ID) values (1,'Treutel Unions',-11,103,'TreutelUnions.com','(225) 506-1703',1);
Insert into DISTRICT (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL,CITY_ID) values (3,'Craig Extensions',23,-150,'CraigExtensions.com','(548) 578-8121',3);
Insert into DISTRICT (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL,CITY_ID) values (2,'Emily Mountains',-88,57,'EmilyMountains.com','012-195-0382',2);
Insert into DISTRICT (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL,CITY_ID) values (4,'Wolff Divide',71,168,'WolffDivide.com','957.815.7394',4);
Insert into DISTRICT (ID,NAME,LATITUDE,LONGITUDE,WEBSITE,TEL,CITY_ID) values (5,'Kurt Valley',-42,26,'KurtValley.com','1-424-020-3272',5);
REM INSERTING into DRIVER
SET DEFINE OFF;
REM INSERTING into EMPLOYEE
SET DEFINE OFF;
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (3,3536992607,'Robyn','Halvorson','robyn_halvorson','U2FsdGVkX1+83TzLaYwCizFKP5W1Zh+qy1juL8Xw/jmZWiti5gH6e3p2vFLVThP2','robyn.halvorson@hotmail.com','(312) 875-9037 x88666','5858313253726','https://s3.amazonaws.com/uifaces/faces/twitter/9lessons/128.jpg',863712.5054,'3078 Lyle Valleys Suite 796',to_date('06-SEP-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (4,5990852621,'Tim','Jerde','tim.jerde','U2FsdGVkX19ViEDjzbTmOUVTHdOxjP9sAeTo+c20W9k=','tim73@hotmail.com','104-441-9284 x5717','187958804503','https://s3.amazonaws.com/uifaces/faces/twitter/necodymiconer/128.jpg',557407.9281,'3410 Marvin Knolls Apt. 634',to_date('30-OCT-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (5,7598268925,'Roxanne','Little','roxanne.little','U2FsdGVkX1+QcdmzvKwI3Zx+r7qrRue+ax1b1j9gMe4=','roxanne.little75@gmail.com','(070) 075-8766 x0101','2408455833554','https://s3.amazonaws.com/uifaces/faces/twitter/andrewcohen/128.jpg',229166.5626,'176 Witting Branch',to_date('30-JAN-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (1,5982900856,'Betty','Dickinson','betty_dickinson','U2FsdGVkX19kMdRKPoC2TUYAf1vfiPczABw1XYKHL9UN4o7WD4MJEJ4HGfEEfYag','betty.dickinson70@gmail.com','510.661.4955 x093','2801007911255','https://s3.amazonaws.com/uifaces/faces/twitter/davidbaldie/128.jpg',834679.4888,'48479 Stiedemann Lane',to_date('26-OCT-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (2,9218996505,'Clara','Reinger','clara_reinger','U2FsdGVkX19jGccKTLAI5BcROYMfCrJ3/XJ4cf454As=','clarareinger55@hotmail.com','961-238-6033','1882834265321','https://s3.amazonaws.com/uifaces/faces/twitter/chrisstumph/128.jpg',367692.7052,'3101 Delia Viaduct Suite 458',to_date('18-JAN-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (6,6188193066,'Flora','Lockman','flora_lockman55','U2FsdGVkX1+aMPOCaPB+kFFrDsFDJKUWsnrgslJhC1qJ2vhMp+haYmaz9REuhvq4','flora.lockman39@gmail.com','070-221-3550 x035','2646702872532','https://s3.amazonaws.com/uifaces/faces/twitter/franciscoamk/128.jpg',423987.6428,'283 Vandervort Motorway',to_date('18-JUL-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (7,5796351718,'Mercedes','Klocko','mercedes.klocko','U2FsdGVkX1/HNO1vUVylgM900iwcchuTNKTzCg824PQmvCyXuUdXPCthUMNW32z9','mercedes04@gmail.com','(699) 648-0716 x316','8808443203216','https://s3.amazonaws.com/uifaces/faces/twitter/ankitind/128.jpg',567672.5078,'8957 Kertzmann Cliff',to_date('23-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (8,7473914377,'Guadalupe','Yost','guadalupe61','U2FsdGVkX1+hngUHskqXbQtUMvehMoDtHx86joWWlKs=','guadalupe.yost91@yahoo.com','780-669-6283 x6636','8761487226693','https://s3.amazonaws.com/uifaces/faces/twitter/switmer777/128.jpg',869109.2384,'073 Turcotte Street',to_date('12-SEP-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (9,5090344092,'Max','Waelchi','max_waelchi','U2FsdGVkX19Shzc9rTCGMI3mv3/Fo6U2Fwr2oOMy/OQ=','max.waelchi92@gmail.com','453.861.8901 x04075','4763173529035','https://s3.amazonaws.com/uifaces/faces/twitter/aaronalfred/128.jpg',898810.841,'792 Bogan Curve',to_date('09-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (10,5348003173,'Ellen','Wolf','ellen.wolf87','U2FsdGVkX19TMZW+uNmZyEBwGtFSqx7kes8upFNS67o=','ellen.wolf03@hotmail.com','1-895-537-6873','2752547799413','https://s3.amazonaws.com/uifaces/faces/twitter/gkaam/128.jpg',988304.4804,'0304 Quigley Mountains Suite 658',to_date('15-SEP-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (11,4850156017,'Gene','Dicki','gene.dicki','U2FsdGVkX1+TVlDUxDG07D0fXmYAvoh8KGItq9sLw9I=','genedicki15@gmail.com','078.828.0279','6536436169250','https://s3.amazonaws.com/uifaces/faces/twitter/demersdesigns/128.jpg',791487.7103,'67026 Doris Dam',to_date('09-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (12,6635979297,'Darla','Hilpert','darlahilpert96','U2FsdGVkX1+451cAt8zmL9FdnQ95wwyVyoTG/tU4TDY=','darla60@hotmail.com','296-464-9597 x1249','1707077121007','https://s3.amazonaws.com/uifaces/faces/twitter/aroon_sharma/128.jpg',902030.8878,'821 Freda Fall Apt. 414',to_date('28-AUG-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (13,2297001722,'Melvin','Cronin','melvin.cronin75','U2FsdGVkX19OW6KIqTPUL4qaaAZTAFwcK3LzDsx8TiPgF1oc0mg2HCG1Os48nDNG','melvincronin63@hotmail.com','633-655-4436','1154233666327','https://s3.amazonaws.com/uifaces/faces/twitter/nitinhayaran/128.jpg',54865.7598,'155 Dietrich Mount',to_date('22-MAR-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (14,3516185584,'Grady','Toy','grady.toy63','U2FsdGVkX1/GgFgpyo11e/GIpWHBWT6TTXVmoJmo18Q=','grady.toy@gmail.com','076.166.3824 x87770','9047801610561','https://s3.amazonaws.com/uifaces/faces/twitter/matbeedotcom/128.jpg',191376.3219,'3975 Bechtelar Rest',to_date('11-AUG-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (15,3204477487,'Alberta','Block','alberta_block','U2FsdGVkX1/B09KVQCx8PCOcicGrmXl9Kl34c85TOsk=','alberta.block@hotmail.com','671-789-1744 x411','8541037490300','https://s3.amazonaws.com/uifaces/faces/twitter/markretzloff/128.jpg',540519.8146,'9197 Doug Curve Apt. 809',to_date('17-JAN-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (16,8038965214,'Ramona','Schmeler','ramona00','U2FsdGVkX1+tmpoZZJabvxkD/eHQZzDVQz2VSmKv+pc=','ramona.schmeler19@yahoo.com','1-230-527-3673 x65857','250702546823','https://s3.amazonaws.com/uifaces/faces/twitter/bennyjien/128.jpg',336490.1696,'91686 Glenn Rue',to_date('23-APR-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (17,1457605733,'Hugo','Doyle','hugo28','U2FsdGVkX184nznP04a5jDxDnZt3WbMR82HWy850sdM=','hugo.doyle@yahoo.com','1-271-182-6077','5785429821362','https://s3.amazonaws.com/uifaces/faces/twitter/chadengle/128.jpg',849966.0025,'98263 Shane Walk Suite 880',to_date('02-JUL-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (18,1964775398,'Emmett','Ward','emmettward54','U2FsdGVkX19ECzbjyZyWPpqoKwKMO5oCQBQgrGQMdA0=','emmett.ward@yahoo.com','460-916-3997','1913244642379','https://s3.amazonaws.com/uifaces/faces/twitter/hoangloi/128.jpg',937970.3135,'4877 Faye Well',to_date('15-DEC-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (19,3424242567,'Brooke','Runolfsson','brooke51','U2FsdGVkX1+iOf7qlwrb5aumGscmaSbt+kRrBaft4zs=','brooke11@yahoo.com','237.696.9139','2275658134551','https://s3.amazonaws.com/uifaces/faces/twitter/Chakintosh/128.jpg',215387.3354,'85101 Lebsack Pines Suite 725',to_date('08-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (20,6524061241,'Eva','Ankunding','eva.ankunding99','U2FsdGVkX1/HYUoToQPYMb0P/7jRb9WgtaVn/qMTHdhh686GYmMB01d2iI3Da7sT','evaankunding20@gmail.com','540-586-4558 x830','4888244327515','https://s3.amazonaws.com/uifaces/faces/twitter/madysondesigns/128.jpg',514310.9503,'07965 Nolan Cape Suite 591',to_date('29-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (21,3516482274,'Ruby','Macejkovic','ruby.macejkovic','U2FsdGVkX18192nVbG0L8akzYatxfMWAznv3VTUOcjGgYCXwm9tn4o7HFvYG778g','ruby79@gmail.com','(294) 108-9925','9124606981451','https://s3.amazonaws.com/uifaces/faces/twitter/alek_djuric/128.jpg',505918.7518,'00849 Dorothy Drive Apt. 757',to_date('19-DEC-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (22,8193744135,'Mike','Vandervort','mike.vandervort02','U2FsdGVkX1/N0DvjyK1iGfh4pOrm/6aKn1CKHdg3+L1nHueBeH4TMoiQardccrc2','mike.vandervort@hotmail.com','(796) 742-8942','3723016034670','https://s3.amazonaws.com/uifaces/faces/twitter/boxmodel/128.jpg',705964.823,'74804 Holly Mews',to_date('18-JUN-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (23,6238217283,'Denise','Rosenbaum','denise.rosenbaum5505','U2FsdGVkX1+0eSA2pSK6dHCCUqk6Hf6aW+uBTIypcvOonbxsoRiuON8EEPsZDAno','deniserosenbaum68@gmail.com','1-126-383-3515','2279330410461','https://s3.amazonaws.com/uifaces/faces/twitter/falling_soul/128.jpg',677926.4644,'4418 Armstrong Spur',to_date('29-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (24,7390188684,'Randall','Moore','randall04','U2FsdGVkX19bPPrxY9ARJkL7ojCn8cSpjxZmvRIh+v8=','randall.moore@yahoo.com','1-780-685-5612 x44975','614639377851','https://s3.amazonaws.com/uifaces/faces/twitter/g3d/128.jpg',230636.1061,'412 Tom Drive',to_date('15-FEB-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (25,8757098088,'Ismael','Brown','ismael.brown3537','U2FsdGVkX19ANruYu88zjfa1Id3nx7eT4fRcntJsfgylws4C9Oq0JUnAi6WGewu/','ismael93@yahoo.com','(255) 557-3369 x30448','1859960569882','https://s3.amazonaws.com/uifaces/faces/twitter/guiiipontes/128.jpg',679904.4927,'443 Lorena Harbors',to_date('16-NOV-17','DD-MON-RR'),null,null,'manager');
REM INSERTING into FOOD
SET DEFINE OFF;
REM INSERTING into FOOD_SHOP
SET DEFINE OFF;
REM INSERTING into HISTORY_ON_TRIP
SET DEFINE OFF;
REM INSERTING into LOCATION
SET DEFINE OFF;
REM INSERTING into MANAGER
SET DEFINE OFF;
Insert into MANAGER (ID,START_DATE) values (3,to_date('27-AUG-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (4,to_date('04-MAR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (5,to_date('24-MAR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (6,to_date('10-JAN-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (7,to_date('16-JAN-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (8,to_date('04-JUN-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (9,to_date('23-APR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (10,to_date('30-AUG-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (11,to_date('19-APR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (12,to_date('25-MAY-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (1,to_date('12-APR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (2,to_date('22-FEB-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (13,to_date('24-NOV-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (14,to_date('21-FEB-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (15,to_date('15-APR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (16,to_date('27-APR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (17,to_date('29-JAN-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (18,to_date('28-MAY-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (19,to_date('23-DEC-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (20,to_date('24-APR-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (21,to_date('20-NOV-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (22,to_date('20-JUL-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (23,to_date('31-JUL-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (24,to_date('13-NOV-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (25,to_date('18-DEC-17','DD-MON-RR'));
REM INSERTING into OFFICE
SET DEFINE OFF;
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (5,'Lemke, Cormier and Bauch Group','9239 Dorothy Ferry',null,5,null,-29.7209,46.0232);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (4,'Schmidt Corp.','08696 Maggie Burg Apt. 573',null,4,null,-80.1699,-6.9894);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (3,'Friesen Ltd.','7691 Volkman Burgs Suite 512',null,3,null,69.0659,34.173);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (2,'Gaylord, Greenfelder and Maggio Inc.','6305 Tyrone Mews',null,2,null,-7.4017,56.5366);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (1,'Kuhn-Carter Inc.','42116 Nina Light',1,1,null,32.947,174.25);
REM INSERTING into PROMOTION
SET DEFINE OFF;
REM INSERTING into PROMOTION_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into REPAIR_EVENT
SET DEFINE OFF;
REM INSERTING into REPAIR_STATION
SET DEFINE OFF;
REM INSERTING into ROUTER_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into SELLER
SET DEFINE OFF;
REM INSERTING into SURCHARGE
SET DEFINE OFF;
REM INSERTING into SURCHARGE_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into TICKET
SET DEFINE OFF;
REM INSERTING into TRANSACTION
SET DEFINE OFF;
REM INSERTING into TRIP
SET DEFINE OFF;
REM INSERTING into TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into WARRANTY
SET DEFINE OFF;
REM INSERTING into WORKER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_PK" ON "BUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROMOTION_PK" ON "PROMOTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPAIR_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPAIR_STATION_PK" ON "REPAIR_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY_PK" ON "CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENT_PK" ON "REPAIR_EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_PK" ON "EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISTRICT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISTRICT_PK" ON "DISTRICT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "WORKER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_PK" ON "ACCOUNT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHARGE_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHARGE_STATION_PK" ON "CHARGE_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROUTER_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUTER_TRIP_DAILY_PK" ON "ROUTER_TRIP_DAILY" ("LOCATION_ID", "TRIP_DAILY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURCHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SURCHARGE_PK" ON "SURCHARGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEPARTMENT_PK" ON "DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOCATION_PK" ON "LOCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURCHARGE_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SURCHARGE_TRIP_DAILY_PK" ON "SURCHARGE_TRIP_DAILY" ("TRIP_DAILY_ID", "SURCHARGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_SHOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD_SHOP_PK" ON "FOOD_SHOP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DRIVER_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVER_UK" ON "DRIVER" ("LICENSE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_UK" ON "EMPLOYEE" ("USERNAME", "SSN", "EMAIL", "BANK_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DRIVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVER_PK" ON "DRIVER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OFFICE_PK" ON "OFFICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SELLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELLER_PK" ON "SELLER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TICKET_PK" ON "TICKET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_TYPE_PK" ON "BUS_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD_PK" ON "FOOD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROMOTION_TRIP_DAILY_PK" ON "PROMOTION_TRIP_DAILY" ("TRIP_DAILY_ID", "PROMOTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSISTANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT_PK" ON "ASSISTANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_PK" ON "CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index WARRANTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WARRANTY_PK" ON "WARRANTY" ("REPAIR_STATION_ID", "BUS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_STATION_PK" ON "BUS_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER_PK" ON "MANAGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRIP_PK" ON "TRIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACTION_PK" ON "TRANSACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRIP_DAILY_PK" ON "TRIP_DAILY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORY_ON_TRIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORY_ON_TRIP_PK" ON "HISTORY_ON_TRIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_UK" UNIQUE ("LICENSE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DRIVER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CITY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CITY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "FOOD" ADD CONSTRAINT "FOOD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "FOOD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEPARTMENT" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "DEPARTMENT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "LOCATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "LOCATION" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "BUS" ADD CONSTRAINT "BUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "BUS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BUS" MODIFY ("REGISTRATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURCHARGE
--------------------------------------------------------

  ALTER TABLE "SURCHARGE" ADD CONSTRAINT "SURCHARGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SURCHARGE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SURCHARGE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPAIR_EVENT
--------------------------------------------------------

  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "ASSISTANT" ADD CONSTRAINT "ASSISTANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASSISTANT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP
--------------------------------------------------------

  ALTER TABLE "TRIP" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WARRANTY
--------------------------------------------------------

  ALTER TABLE "WARRANTY" MODIFY ("REPAIR_STATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WARRANTY" MODIFY ("BUS_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_PK" PRIMARY KEY ("REPAIR_STATION_ID", "BUS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "TRIP_DAILY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" ADD CONSTRAINT "DISTRICT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DISTRICT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DISTRICT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "OFFICE" ADD CONSTRAINT "OFFICE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "OFFICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OFFICE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ACCOUNT" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT" MODIFY ("OWNER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS_STATION
--------------------------------------------------------

  ALTER TABLE "BUS_STATION" ADD CONSTRAINT "BUS_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "BUS_STATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS_TYPE
--------------------------------------------------------

  ALTER TABLE "BUS_TYPE" ADD CONSTRAINT "BUS_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "BUS_TYPE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BUS_TYPE" MODIFY ("BRAND" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "TICKET" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" MODIFY ("TRIP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPAIR_STATION
--------------------------------------------------------

  ALTER TABLE "REPAIR_STATION" ADD CONSTRAINT "REPAIR_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "REPAIR_STATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_UK_ID" UNIQUE ("USERNAME", "SSN", "EMAIL", "BANK_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("SSN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_PK" PRIMARY KEY ("TRIP_DAILY_ID", "SURCHARGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SURCHARGE_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SURCHARGE_TRIP_DAILY" MODIFY ("SURCHARGE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_PK" PRIMARY KEY ("TRIP_DAILY_ID", "PROMOTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PROMOTION_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROMOTION_TRIP_DAILY" MODIFY ("PROMOTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOOD_SHOP
--------------------------------------------------------

  ALTER TABLE "FOOD_SHOP" ADD CONSTRAINT "FOOD_SHOP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "FOOD_SHOP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" ADD CONSTRAINT "SELLER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SELLER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_PK" PRIMARY KEY ("LOCATION_ID", "TRIP_DAILY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ROUTER_TRIP_DAILY" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROUTER_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "PROMOTION" ADD CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PROMOTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROMOTION" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKER
--------------------------------------------------------

  ALTER TABLE "WORKER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "WORKER" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHARGE_STATION
--------------------------------------------------------

  ALTER TABLE "CHARGE_STATION" ADD CONSTRAINT "CHARGE_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CHARGE_STATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "MANAGER" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MANAGER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORY_ON_TRIP
--------------------------------------------------------

  ALTER TABLE "HISTORY_ON_TRIP" ADD CONSTRAINT "HISTORY_ON_TRIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HISTORY_ON_TRIP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK_OWNER" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "ASSISTANT" ADD CONSTRAINT "ASSISTANT_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "BUS" ADD CONSTRAINT "BUS_FK_TYPE" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUS_STATION
--------------------------------------------------------

  ALTER TABLE "BUS_STATION" ADD CONSTRAINT "BUS_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHARGE_STATION
--------------------------------------------------------

  ALTER TABLE "CHARGE_STATION" ADD CONSTRAINT "CHARGE_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CITY" ADD CONSTRAINT "CITY_FK1" FOREIGN KEY ("CENTER_DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_MANAGER" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "MANAGER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_OFFICE" FOREIGN KEY ("OFFICE_ID")
	  REFERENCES "OFFICE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" ADD CONSTRAINT "DISTRICT_FK_CITY" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CITY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK_DEPART" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK_SUPERVISOR" FOREIGN KEY ("SUPERVISOR_ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "FOOD" ADD CONSTRAINT "FOOD_FK" FOREIGN KEY ("FOOD_SHOP_ID")
	  REFERENCES "FOOD_SHOP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOOD_SHOP
--------------------------------------------------------

  ALTER TABLE "FOOD_SHOP" ADD CONSTRAINT "FOOD_SHOP_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORY_ON_TRIP
--------------------------------------------------------

  ALTER TABLE "HISTORY_ON_TRIP" ADD CONSTRAINT "HISTORY_ON_TRIP_FK_TRIP" FOREIGN KEY ("TRIP_ID")
	  REFERENCES "TRIP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "OFFICE" ADD CONSTRAINT "OFFICE_FK_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_FK_PRO" FOREIGN KEY ("PROMOTION_ID")
	  REFERENCES "PROMOTION" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_EVENT
--------------------------------------------------------

  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK1" FOREIGN KEY ("ASSISTANCE_ID")
	  REFERENCES "ASSISTANT" ("ID") ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_BUS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "BUS" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_CREATOR" FOREIGN KEY ("CREATOR_ID")
	  REFERENCES "MANAGER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "DRIVER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_STATION" FOREIGN KEY ("REPAIR_STATION_ID")
	  REFERENCES "REPAIR_STATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_STATION
--------------------------------------------------------

  ALTER TABLE "REPAIR_STATION" ADD CONSTRAINT "REPAIR_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_FK_LOC" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" ADD CONSTRAINT "SELLER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_FK_SUR" FOREIGN KEY ("SURCHARGE_ID")
	  REFERENCES "SURCHARGE" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_FK_TRANSACTION" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANSACTION" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_FK_TRIP" FOREIGN KEY ("TRIP_ID")
	  REFERENCES "TRIP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_ACCOUNT" FOREIGN KEY ("ACCOUNT")
	  REFERENCES "ACCOUNT" ("EMAIL") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_SELLER" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "SELLER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIP
--------------------------------------------------------

  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_ASSISTANT" FOREIGN KEY ("ASSISTANT_ID")
	  REFERENCES "ASSISTANT" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_BUS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "BUS" ("ID") ENABLE;
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_DAILY" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "DRIVER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_AR_ID" FOREIGN KEY ("ARRIVE_STATION_ID")
	  REFERENCES "BUS_STATION" ("ID") ENABLE;
 
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_BUS_TYPE" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_DE_ID" FOREIGN KEY ("DEPART_STATION_ID")
	  REFERENCES "BUS_STATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WARRANTY
--------------------------------------------------------

  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_FK_BUS" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_FK_STATION" FOREIGN KEY ("REPAIR_STATION_ID")
	  REFERENCES "REPAIR_STATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKER
--------------------------------------------------------

  ALTER TABLE "WORKER" ADD CONSTRAINT "WORKER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
