--------------------------------------------------------
--  File created - Friday-April-27-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ACCOUNT" 
   (	"EMAIL" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"SURPLUS" NUMBER(8,0), 
	"OWNER_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ACCOUNT"."SURPLUS" IS 'so du tai khoan';
--------------------------------------------------------
--  DDL for Table ASSISTANT
--------------------------------------------------------

  CREATE TABLE "ASSISTANT" 
   (	"ID" NUMBER(15,0), 
	"TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS
--------------------------------------------------------

  CREATE TABLE "BUS" 
   (	"ID" NUMBER(6,0), 
	"BUS_TYPE_ID" NUMBER(3,0), 
	"REGISTRATION" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(15,5), 
	"STATUS" NVARCHAR2(20), 
	"MILES" NUMBER(15,4), 
	"BUY_DATE" DATE, 
	"WARRANTY_MONTH" NUMBER(2,0), 
	"WARRANTY_MILES" NUMBER(6,0), 
	"DESCRIPTION" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BUS"."REGISTRATION" IS 'số đăng ký xe';
   COMMENT ON COLUMN "BUS"."STATUS" IS 'mới, cũ, tốt, ...';
   COMMENT ON COLUMN "BUS"."MILES" IS 'số dặm đã chaỵ, cập nhật theo lịch hẹn, không cần real-time';
   COMMENT ON COLUMN "BUS"."WARRANTY_MONTH" IS 'số tháng tối đa cho bảo hành, eg. 18 month';
   COMMENT ON COLUMN "BUS"."WARRANTY_MILES" IS 'số dặm tối đa cho bảo hành, eg. 150000 km';
   COMMENT ON COLUMN "BUS"."DESCRIPTION" IS 'eg. linh kiện thiếu sót';
--------------------------------------------------------
--  DDL for Table BUS_STATION
--------------------------------------------------------

  CREATE TABLE "BUS_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ESTABLISH_DATE" DATE, 
	"OWNER_NAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS_TYPE
--------------------------------------------------------

  CREATE TABLE "BUS_TYPE" 
   (	"ID" NUMBER(3,0), 
	"BRAND" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"SEATS" NUMBER(3,0), 
	"SPEED" NUMBER(7,2), 
	"CAPACITY_FUEL" NUMBER(7,2), 
	"MASS_NO_LOAD" NUMBER(7,2), 
	"MASS_ALL" NUMBER(7,2), 
	"HEIGHT" NUMBER(7,2), 
	"WIDTH" NUMBER(7,2), 
	"LENGTH" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BUS_TYPE"."BRAND" IS 'eg. THAO, AERO EXPRESS, MOBIHOME';
   COMMENT ON COLUMN "BUS_TYPE"."MODEL" IS 'eg. version, year, ...';
   COMMENT ON COLUMN "BUS_TYPE"."SEATS" IS 'eg. 80, 60, 40, 41, 43';
   COMMENT ON COLUMN "BUS_TYPE"."SPEED" IS 'eg. 95 km/h';
   COMMENT ON COLUMN "BUS_TYPE"."CAPACITY_FUEL" IS 'eg. 240 l';
   COMMENT ON COLUMN "BUS_TYPE"."MASS_NO_LOAD" IS 'eg. 10500 kg';
   COMMENT ON COLUMN "BUS_TYPE"."MASS_ALL" IS 'eg. 15700 kg';
   COMMENT ON COLUMN "BUS_TYPE"."HEIGHT" IS 'unit: m';
   COMMENT ON COLUMN "BUS_TYPE"."WIDTH" IS 'unit: m';
   COMMENT ON COLUMN "BUS_TYPE"."LENGTH" IS 'unit: m';
--------------------------------------------------------
--  DDL for Table CHARGE_STATION
--------------------------------------------------------

  CREATE TABLE "CHARGE_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ESTABLISH_DATE" DATE, 
	"OWNER_NAME" NVARCHAR2(50), 
	"DATE_APPLY" DATE, 
	"DATE_END" DATE, 
	"FEE_PER_BUS" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "CITY" 
   (	"ID" NUMBER(3,0), 
	"NAME" NVARCHAR2(20), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"TEL_CODE" NUMBER(4,0), 
	"ZIP_CODE" NUMBER(7,0), 
	"AREA_CODE" NUMBER(3,0), 
	"CENTER_DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(12,0), 
	"FIRST_NAME" NVARCHAR2(20), 
	"LAST_NAME" NVARCHAR2(20), 
	"TEL" VARCHAR2(15 BYTE), 
	"ADDRESS" NVARCHAR2(200), 
	"FEED_BACK" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "DEPARTMENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"MANAGER_ID" NUMBER(15,0), 
	"OFFICE_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEPARTMENT"."TYPE" IS 'eg. Research';
   COMMENT ON COLUMN "DEPARTMENT"."NAME" IS 'eg. Phòng nghiên cứu';
--------------------------------------------------------
--  DDL for Table DISTRICT
--------------------------------------------------------

  CREATE TABLE "DISTRICT" 
   (	"ID" NUMBER(5,0), 
	"NAME" NVARCHAR2(50), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"CITY_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DRIVER
--------------------------------------------------------

  CREATE TABLE "DRIVER" 
   (	"ID" NUMBER(15,0), 
	"LICENSE_NUMBER" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(15,0), 
	"FIRST_NAME" NVARCHAR2(50), 
	"LAST_NAME" NVARCHAR2(50), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(50 BYTE), 
	"BANK_ACCOUNT" VARCHAR2(20 BYTE), 
	"PHOTO_URL" VARCHAR2(500 BYTE), 
	"SALARY" NUMBER(15,4), 
	"ADDRESS" NVARCHAR2(200), 
	"JOIN_DATE" DATE, 
	"SUPERVISOR_ID" NUMBER(15,0), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "EMPLOYEE"."ROLE" IS 'manager, driver, assistant, worker, seller';
--------------------------------------------------------
--  DDL for Table FOOD
--------------------------------------------------------

  CREATE TABLE "FOOD" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" NVARCHAR2(50), 
	"PRICE" NUMBER(10,5), 
	"FOR_VEGETARIAN" NUMBER(1,0), 
	"DRINKABLE" NUMBER(1,0), 
	"FOOD_SHOP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOOD_SHOP
--------------------------------------------------------

  CREATE TABLE "FOOD_SHOP" 
   (	"ID" VARCHAR2(10 BYTE), 
	"CAPACITY" NUMBER(4,0), 
	"QUALITY" NUMBER(3,0), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORY_ON_TRIP
--------------------------------------------------------

  CREATE TABLE "HISTORY_ON_TRIP" 
   (	"ID" NUMBER(8,0), 
	"TRIP_ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" NVARCHAR2(200), 
	"FEE" NUMBER(15,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "LOCATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" NVARCHAR2(50), 
	"ADDRESS" NVARCHAR2(200), 
	"LATITUDE" NUMBER(3,0), 
	"LONGTITUDE" NUMBER(3,0), 
	"OPEN_TIME" DATE, 
	"CLOSE_TIME" DATE, 
	"TEL" VARCHAR2(15 BYTE), 
	"DISTRICT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LOCATION"."LATITUDE" IS '-86 to 86';
   COMMENT ON COLUMN "LOCATION"."LONGTITUDE" IS '-180 to 180';
   COMMENT ON COLUMN "LOCATION"."OPEN_TIME" IS 'hh:mm';
   COMMENT ON COLUMN "LOCATION"."CLOSE_TIME" IS 'hh:mm';
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "MANAGER" 
   (	"ID" NUMBER(15,0), 
	"START_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFICE
--------------------------------------------------------

  CREATE TABLE "OFFICE" 
   (	"ID" NUMBER(3,0), 
	"NAME" NVARCHAR2(100), 
	"ADDRESS" NVARCHAR2(200), 
	"IS_HEADQUATER" NUMBER(1,0), 
	"DISTRICT_ID" NUMBER(5,0), 
	"HOTLINE" VARCHAR2(50 BYTE), 
	"LATITUDE" NUMBER(15,5), 
	"LONGITUDE" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "PROMOTION" 
   (	"ID" NUMBER(6,0), 
	"NAME" NVARCHAR2(100), 
	"CODE" VARCHAR2(15 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"DESCRIPTION" NVARCHAR2(500), 
	"CUT_PRICE" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "PROMOTION_TRIP_DAILY" 
   (	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"PROMOTION_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIR_EVENT
--------------------------------------------------------

  CREATE TABLE "REPAIR_EVENT" 
   (	"ID" NUMBER(6,0), 
	"BUS_ID" NUMBER(8,0), 
	"REPAIR_STATION_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" NVARCHAR2(200), 
	"TIME_APPLY" DATE, 
	"CREATOR_ID" NUMBER(15,0), 
	"DRIVER_ID" NUMBER(15,0), 
	"SPENDING" NUMBER(8,4), 
	"ASSISTANCE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIR_STATION
--------------------------------------------------------

  CREATE TABLE "REPAIR_STATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"QUALITY" NUMBER(3,0), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "ROUTER_TRIP_DAILY" 
   (	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"ORDER_ON_ROUTER" NUMBER(3,0), 
	"DISTANCE_TO" NUMBER(6,0), 
	"DURATION_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ROUTER_TRIP_DAILY"."DISTANCE_TO" IS 'khoang cach tu dau den location nay';
   COMMENT ON COLUMN "ROUTER_TRIP_DAILY"."DURATION_TO" IS 'thoi gian (ms) de den cho nay';
   COMMENT ON TABLE "ROUTER_TRIP_DAILY"  IS 'Lộ trình trên chuyến đi';
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "SELLER" 
   (	"ID" NUMBER(15,0), 
	"EXP_TRANSACTION" NUMBER(15,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURCHARGE
--------------------------------------------------------

  CREATE TABLE "SURCHARGE" 
   (	"ID" NUMBER(6,0), 
	"NAME" NVARCHAR2(100), 
	"CODE" VARCHAR2(15 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"DESCRIPTION" NVARCHAR2(500), 
	"INCREASE_FEE" NUMBER(15,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "SURCHARGE_TRIP_DAILY" 
   (	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"SURCHARGE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "TICKET" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(40 BYTE), 
	"TRANSACTION_ID" NUMBER(15,0), 
	"TRIP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TRANSACTION" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"CUSTOMER_ID" NUMBER(15,0), 
	"SELLER_ID" NUMBER(15,0), 
	"ACCOUNT" VARCHAR2(100 BYTE), 
	"TOTAL_PRICE" NUMBER(15,4), 
	"PAYMENT_METHOD" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TRANSACTION"."PAYMENT_METHOD" IS 'office, online';
   COMMENT ON COLUMN "TRANSACTION"."STATUS" IS 'finished, paid, pending, ...';
--------------------------------------------------------
--  DDL for Table TRIP
--------------------------------------------------------

  CREATE TABLE "TRIP" 
   (	"ID" VARCHAR2(40 BYTE), 
	"TRIP_DAILY_ID" VARCHAR2(20 BYTE), 
	"DEPART_DATE" DATE, 
	"BUS_ID" NUMBER(5,0), 
	"DRIVER_ID" NUMBER(15,0), 
	"ASSISTANT_ID" NUMBER(15,0), 
	"IS_COMPLETE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TRIP"."DEPART_DATE" IS 'ngày khởi hành';
   COMMENT ON COLUMN "TRIP"."IS_COMPLETE" IS '(1/0) - true/false';
--------------------------------------------------------
--  DDL for Table TRIP_DAILY
--------------------------------------------------------

  CREATE TABLE "TRIP_DAILY" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"DEPART_STATION_ID" VARCHAR2(10 BYTE), 
	"ARRIVE_STATION_ID" VARCHAR2(10 BYTE), 
	"DEPART_TIME" DATE, 
	"ARRIVE_TIME" DATE, 
	"DURATION" TIMESTAMP (6), 
	"PRICE" NUMBER(15,4), 
	"DISTANCE" NUMBER(15,0), 
	"HOTLINE" VARCHAR2(15 BYTE), 
	"BUS_TYPE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TRIP_DAILY"."DEPART_STATION_ID" IS 'trạm khởi hành';
   COMMENT ON COLUMN "TRIP_DAILY"."ARRIVE_STATION_ID" IS 'trạm đến';
   COMMENT ON COLUMN "TRIP_DAILY"."DEPART_TIME" IS 'gi�? khởi hành';
   COMMENT ON COLUMN "TRIP_DAILY"."ARRIVE_TIME" IS 'gi�? đến';
--------------------------------------------------------
--  DDL for Table WARRANTY
--------------------------------------------------------

  CREATE TABLE "WARRANTY" 
   (	"REPAIR_STATION_ID" VARCHAR2(20 BYTE), 
	"BUS_TYPE_ID" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "WARRANTY"  IS 'Warranty relation between bus_type with repair station';
--------------------------------------------------------
--  DDL for Table WORKER
--------------------------------------------------------

  CREATE TABLE "WORKER" 
   (	"ID" NUMBER(15,0), 
	"JOB_TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ACCOUNT
SET DEFINE OFF;
REM INSERTING into ASSISTANT
SET DEFINE OFF;
REM INSERTING into BUS
SET DEFINE OFF;
REM INSERTING into BUS_STATION
SET DEFINE OFF;
REM INSERTING into BUS_TYPE
SET DEFINE OFF;
REM INSERTING into CHARGE_STATION
SET DEFINE OFF;
REM INSERTING into CITY
SET DEFINE OFF;
REM INSERTING into CUSTOMER
SET DEFINE OFF;
REM INSERTING into DEPARTMENT
SET DEFINE OFF;
REM INSERTING into DISTRICT
SET DEFINE OFF;
REM INSERTING into DRIVER
SET DEFINE OFF;
REM INSERTING into EMPLOYEE
SET DEFINE OFF;
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (31,1121269048,'Henry','Pacocha','henry_pacocha','U2FsdGVkX19sg/5gZj2Xvia5W+mCZyNf2NnHPawq4zY=','henry.pacocha99@gmail.com','1-604-810-8072 x09010','4350932873900','https://s3.amazonaws.com/uifaces/faces/twitter/eddiechen/128.jpg',909352.792,'9537 Larson Place',to_date('29-APR-17','DD-MON-RR'),3,null,'seller');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (27,8979997603,'Johanna','Lindgren','johanna.lindgren63','U2FsdGVkX1+9DHhPRj4xqyIJRI5qFmn8WCMlx1SJEVF5iv4VBOgRvfUI0Jsb+nnf','johannalindgren09@hotmail.com','(973) 118-5623 x589','3566878915216','https://s3.amazonaws.com/uifaces/faces/twitter/vitorleal/128.jpg',192450.7762,'521 Lela Highway Suite 357',to_date('16-MAR-18','DD-MON-RR'),5,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (32,7767098778,'Theresa','Jacobson','theresa_jacobson','U2FsdGVkX188eDrlbM5nhsiuFMyQZ42IxEfvXoZCGEH0vqLlSeEk4eRoI5IuSTjB','theresa.jacobson72@hotmail.com','(912) 710-5591','4170345001452','https://s3.amazonaws.com/uifaces/faces/twitter/madewulf/128.jpg',946336.3208,'77750 Glover Views Apt. 993',to_date('27-NOV-17','DD-MON-RR'),5,null,'seller');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (33,7884786243,'Olivia','Mraz','olivia46','U2FsdGVkX1/C4q0FLH1Vwg3Dv0vn1cl/8cZorcjvcqs=','olivia16@gmail.com','(729) 505-3368 x788','6170161525140','https://s3.amazonaws.com/uifaces/faces/twitter/karolkrakowiak_/128.jpg',593776.0876,'903 Rodney Glen',to_date('26-SEP-17','DD-MON-RR'),4,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (34,1542918526,'Katrina','Muller','katrina_muller','U2FsdGVkX1+aRU7XYGNsIeJycvYz1Ax6KzoUr8UmLCc=','katrina.muller@gmail.com','531.966.3430 x977','6878085858372','https://s3.amazonaws.com/uifaces/faces/twitter/emmeffess/128.jpg',552984.4225,'8697 Jason Mountains',to_date('07-MAR-18','DD-MON-RR'),4,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (35,3658812436,'Leland','Morissette','leland.morissette88','U2FsdGVkX19GcRiT0S2ehhbtsjXTRbAFQPxNNBKwhI2pGzmHhUtGgO8rNP9vxZzp','lelandmorissette45@hotmail.com','879.359.7421','5684004525511','https://s3.amazonaws.com/uifaces/faces/twitter/jeremiaha/128.jpg',540311.3484,'33305 Rau Loaf',to_date('27-JAN-18','DD-MON-RR'),1,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (36,2906450559,'Marta','Romaguera','marta.romaguera81','U2FsdGVkX19A59Ls0LuBmidVjNefJbxDW/Mye2eKBfKuKIXxnWKyuToCn7hbC2/Y','marta.romaguera91@yahoo.com','(449) 904-7052 x4805','8158359691285','https://s3.amazonaws.com/uifaces/faces/twitter/josep_martins/128.jpg',991923.4232,'96938 Lillian Flats Apt. 938',to_date('05-JUN-17','DD-MON-RR'),3,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (37,9140968881,'Gilberto','Will','gilberto.will','U2FsdGVkX19TKxZ3sw2y2YwC1K4lMFieqo3a6Na4uRc=','gilberto.will@yahoo.com','518.496.8416','2921142413995','https://s3.amazonaws.com/uifaces/faces/twitter/agustincruiz/128.jpg',65882.6537,'462 Feil Park',to_date('30-APR-17','DD-MON-RR'),1,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (38,3263726671,'Emily','Dietrich','emilydietrich11','U2FsdGVkX19OFP7LVfhiA2WkdX4AQACnyCf3X1tumSfKXdsvXxg68V+YlK+oHCzP','emily.dietrich71@yahoo.com','215.533.7608','8248344796547','https://s3.amazonaws.com/uifaces/faces/twitter/joeymurdah/128.jpg',563683.9676,'8954 Johnathan Crossing',to_date('21-JAN-18','DD-MON-RR'),4,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (39,2177054009,'Evelyn','Kilback','evelyn.kilback','U2FsdGVkX19EiMFESlm+kSReWr6Cm//4re1Kd+8+XaM=','evelyn.kilback18@yahoo.com','(757) 452-1501 x930','86646997988','https://s3.amazonaws.com/uifaces/faces/twitter/dallasbpeters/128.jpg',876791.5467,'819 Lora Underpass',to_date('15-NOV-17','DD-MON-RR'),3,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (41,6100762715,'Dianne','Padberg','dianne_padberg38','U2FsdGVkX19nWl0PS0a94Xj7R6ZwCQj13ZsLKvGW5xZlNzwAv6z/8bLpTFhiN5Wd','dianne21@gmail.com','1-740-411-6199 x696','734004958483','https://s3.amazonaws.com/uifaces/faces/twitter/ismail_biltagi/128.jpg',393462.9059,'705 Gusikowski Valleys',to_date('21-OCT-17','DD-MON-RR'),1,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (40,2183860362,'Ernestine','Mante','ernestine_mante44','U2FsdGVkX1+9ncqunsA+jlueNs/A65J3QB/FTTPOchYFDHfWiTKOjIEFpNTKgiDm','ernestinemante78@gmail.com','(172) 287-7067','4264739407473','https://s3.amazonaws.com/uifaces/faces/twitter/shesgared/128.jpg',496173.764,'62102 Veum Locks Suite 184',to_date('30-JAN-18','DD-MON-RR'),3,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (43,5961556601,'Cecil','Hirthe','cecilhirthe02','U2FsdGVkX1/DF8AakS5rGtu07tYcaGGN2eQZlN+mnQU=','cecil.hirthe29@hotmail.com','866-876-8206 x02904','9959391239619','https://s3.amazonaws.com/uifaces/faces/twitter/magugzbrand2d/128.jpg',867485.1984,'87910 Samantha Centers Suite 117',to_date('05-MAR-18','DD-MON-RR'),1,null,'assistant');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (44,3498766395,'Hubert','Robel','hubert.robel13','U2FsdGVkX18sPikbMRjs6xTtxyjVwwDbaqui7/MAEOQ=','hubert.robel00@gmail.com','246-523-3248 x40798','5292217346250','https://s3.amazonaws.com/uifaces/faces/twitter/denisepires/128.jpg',818327.1698,'48254 Emard Throughway Suite 090',to_date('24-JUN-17','DD-MON-RR'),3,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (46,2340698219,'Chris','Sawayn','chris.sawayn','U2FsdGVkX1+VeytEbRXshPqEg1ja5tTYwkkFrYfZ8nk=','chris.sawayn@hotmail.com','713.945.1527','2875197820936','https://s3.amazonaws.com/uifaces/faces/twitter/laurengray/128.jpg',825817.9849,'54701 Inez Turnpike Suite 542',to_date('19-JUN-17','DD-MON-RR'),5,null,'seller');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (47,3086005964,'Jo','Weissnat','jo_weissnat','U2FsdGVkX1+X8wQuollB7YB50mjamz9D6sOol/kkOzA=','jo10@gmail.com','624-726-1637','70768486876','https://s3.amazonaws.com/uifaces/faces/twitter/gauravjassal/128.jpg',285658.8239,'24125 McLaughlin Unions Apt. 833',to_date('24-AUG-17','DD-MON-RR'),3,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (48,3540519071,'Marjorie','Muller','marjorie.muller','U2FsdGVkX1+ryRftoE8ltYDKt5ZoREBtniQc5+lrtyCmPJ13xiN8s75a8+ixLsuQ','marjorie83@yahoo.com','159.491.0613','1388490298961','https://s3.amazonaws.com/uifaces/faces/twitter/nickfratter/128.jpg',692711.9063,'49032 Mable Course',to_date('23-AUG-17','DD-MON-RR'),1,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (49,4111660997,'Sherri','Braun','sherri.braun81','U2FsdGVkX1+uc91TSQuwKgrJX8EbbFmhsWRXHthos7M=','sherri72@hotmail.com','278-816-7527 x56761','5478091102001','https://s3.amazonaws.com/uifaces/faces/twitter/xravil/128.jpg',658178.1138,'60007 Hane Mountains',to_date('19-AUG-17','DD-MON-RR'),5,null,'assistant');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (50,8047106201,'Douglas','Kreiger','douglas13','U2FsdGVkX1/PK2+UrAR24T7O7H9qAeb7ppRJDXHqbkM=','douglaskreiger65@yahoo.com','667-353-1138 x985','9907542343108','https://s3.amazonaws.com/uifaces/faces/twitter/kijanmaharjan/128.jpg',215284.6011,'95570 Jacobs Crossroad',to_date('30-JAN-18','DD-MON-RR'),4,null,'assistant');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (3,5714651056,'Darrell','Kling','darrell_kling96','U2FsdGVkX1+ywiDAp+NWle4G30catdRL/1zwiEzo4DkhVk9GKVljbPHWe3ET/x7G','darrellkling99@yahoo.com','1-591-691-2694 x90114','6398782192513','https://s3.amazonaws.com/uifaces/faces/twitter/abdullindenis/128.jpg',983631.9055,'13147 Friesen Stravenue Apt. 853',to_date('17-JUL-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (4,4698151031,'Patsy','Lockman','patsy.lockman15','U2FsdGVkX188EJmT0N3YltjuSvIHjbUyLvtISNElEWcTlY9F32Xa7pNKRlPweW8f','patsy.lockman70@yahoo.com','(268) 674-6388 x35339','3416162727223','https://s3.amazonaws.com/uifaces/faces/twitter/arindam_/128.jpg',685639.9586,'999 Hackett Stream',to_date('28-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (5,8370254156,'Michele','Carroll','michele.carroll','U2FsdGVkX1+jZTxotdScUfjD8S1zvRSqhUdOJezTtlpKhcHPGVEc8vPXp8P15raB','michele.carroll@yahoo.com','774.213.7071 x313','6392126740409','https://s3.amazonaws.com/uifaces/faces/twitter/abdots/128.jpg',219448.1162,'782 Doug Forks',to_date('08-OCT-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (6,9059252028,'Jane','Schroeder','jane.schroeder3490','U2FsdGVkX19IFzyUVqop+lkyXIiLSGJy1oOUMGwgCMztd4QGHQ5V2tDxKNBv/YNz','jane51@gmail.com','176.082.8969','8423615868347','https://s3.amazonaws.com/uifaces/faces/twitter/nsamoylov/128.jpg',790010.3667,'065 Irvin Manor Suite 732',to_date('02-MAY-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (7,7298257986,'Lila','Simonis','lila.simonis6934','U2FsdGVkX1/E5Hm+ZoDR1A5zyfTVGTw/qjOukAXnnRL89GndvB6sE2MKM5qaXyiz','lilasimonis42@yahoo.com','(492) 952-3055 x2298','6037517367890','https://s3.amazonaws.com/uifaces/faces/twitter/fran_mchamy/128.jpg',854958.3149,'810 Senger Cliff Apt. 366',to_date('28-JUN-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (8,4671830608,'June','Bradtke','june.bradtke','U2FsdGVkX19gsLI/M0c3KPPRz2UwNh0W34lY4uhnRO4=','june.bradtke@gmail.com','080-828-9051 x96251','810396617621','https://s3.amazonaws.com/uifaces/faces/twitter/lanceguyatt/128.jpg',929923.8086,'8802 Gary View',to_date('24-OCT-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (9,4990327085,'Darin','Hackett','darin.hackett','U2FsdGVkX1/N7JoBL/xLVWNl/qqtk8bwFNjkYmyXRp4=','darinhackett80@gmail.com','1-287-991-6215 x997','5050310177849','https://s3.amazonaws.com/uifaces/faces/twitter/ruehldesign/128.jpg',328652.4737,'5117 Runolfsson Landing Suite 248',to_date('19-NOV-17','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (10,1479370847,'Reginald','Emmerich','reginald_emmerich12','U2FsdGVkX1++vbWAo0E1YhoWeELY1fvjRKmdA27mDgX0If49ubXeZNcYQgYwpJrN','reginaldemmerich45@yahoo.com','1-165-112-3140','5452016877494','https://s3.amazonaws.com/uifaces/faces/twitter/overra/128.jpg',370996.5559,'85373 Heller Prairie',to_date('21-APR-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (11,8275174672,'Dominic','Marvin','dominicmarvin29','U2FsdGVkX19Cfsk/x3+tvScDsFoQKEgoL8THKa278UAWhnbsQjv7fynhEZt1bJQB','dominic29@gmail.com','(138) 256-6638 x4152','5397889736681','https://s3.amazonaws.com/uifaces/faces/twitter/mattsapii/128.jpg',662024.9175,'85528 Grant Fall',to_date('29-MAY-17','DD-MON-RR'),3,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (12,2853208193,'Kelly','Abbott','kelly_abbott','U2FsdGVkX19KhEUzkbfJyWgNpPsHRVeb+GKSEAoWGG8=','kelly07@yahoo.com','280-746-2263','9303896158390','https://s3.amazonaws.com/uifaces/faces/twitter/denisepires/128.jpg',984172.5057,'4500 Kuvalis Common Apt. 549',to_date('16-APR-18','DD-MON-RR'),4,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (1,5631407779,'Lynne','Kunze','lynne_kunze','U2FsdGVkX1+S3FXWj3mEyRLLWg+EMLSoBmhsfyLUE80=','lynnekunze68@gmail.com','613.543.9770 x87646','4166205910945','https://s3.amazonaws.com/uifaces/faces/twitter/barputro/128.jpg',129041.4105,'7031 Stroman Springs',to_date('01-FEB-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (2,1677121685,'Betty','Bednar','betty.bednar7321','U2FsdGVkX1+y58MyOFxvOHnNeknyx5nLvjJ2kYFnoyulBH+C5+94QNT/91Ay+vL6','bettybednar46@gmail.com','573.625.3169 x5639','1529845684530','https://s3.amazonaws.com/uifaces/faces/twitter/_williamguerra/128.jpg',104746.9481,'6842 Conn Canyon',to_date('05-JAN-18','DD-MON-RR'),null,null,'manager');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (14,7600565839,'Candace','Zieme','candace30','U2FsdGVkX1+UWbTIVI73R3zgogEDsYsYXBYjiOtBxrI=','candacezieme18@yahoo.com','(301) 241-2801','6066904505499','https://s3.amazonaws.com/uifaces/faces/twitter/osmanince/128.jpg',65680.8653,'6058 Valerie Mission Apt. 942',to_date('29-AUG-17','DD-MON-RR'),4,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (15,8250655137,'Luz','Huels','luzhuels90','U2FsdGVkX1+aupkGNJSTlaSEJPEbXWaTiPP8Ihou3q8=','luz.huels13@gmail.com','562.607.5650 x01788','159811181371','https://s3.amazonaws.com/uifaces/faces/twitter/balakayuriy/128.jpg',478761.6052,'09076 Lowe View',to_date('08-OCT-17','DD-MON-RR'),2,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (20,7673647330,'Derek','Cartwright','derek_cartwright84','U2FsdGVkX1+nlPmyR2nMP+lb9ECa9lNZgPeYOftnBmlhQwG4mq/4rFImr9oo/iCJ','derek.cartwright@gmail.com','334-500-8046','6648129696621','https://s3.amazonaws.com/uifaces/faces/twitter/raphaelnikson/128.jpg',377466.3626,'9152 Evan Course',to_date('24-APR-18','DD-MON-RR'),1,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (18,2008050775,'Dominic','Littel','dominic.littel','U2FsdGVkX19BBTW4MP3GJOPGXEsC5eNrqiMR1/pVhjM=','dominic67@yahoo.com','736-854-7486 x17183','4041200584744','https://s3.amazonaws.com/uifaces/faces/twitter/amayvs/128.jpg',895002.8679,'336 Damon Orchard',to_date('12-NOV-17','DD-MON-RR'),1,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (19,2509668553,'Mildred','Miller','mildred_miller','U2FsdGVkX1/PfgKLwxwkpkkBflCT1khmhN7zKSxaCrs=','mildred.miller@gmail.com','1-518-818-1548 x12211','3083138834993','https://s3.amazonaws.com/uifaces/faces/twitter/kapaluccio/128.jpg',644942.6729,'436 Pacocha Neck Apt. 718',to_date('15-FEB-18','DD-MON-RR'),3,null,'worker');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (17,8843279282,'Brenda','Marvin','brenda_marvin','U2FsdGVkX1+tj0ocZaDrro9j1qXMM7hnJExEKwFYNoQ=','brenda.marvin62@gmail.com','1-256-734-2036','5556464466241','https://s3.amazonaws.com/uifaces/faces/twitter/mactopus/128.jpg',202159.7863,'78480 O''Reilly Trace',to_date('19-JUN-17','DD-MON-RR'),1,null,'assistant');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (21,9253992242,'Clarence','Quigley','clarence90','U2FsdGVkX18vhsXWRLKT7j1LrhE4+iWu/PZao6PqFSI=','clarencequigley71@gmail.com','918.714.3111 x061','3867705297992','https://s3.amazonaws.com/uifaces/faces/twitter/chadengle/128.jpg',795726.1769,'2442 Hoeger Drive',to_date('23-OCT-17','DD-MON-RR'),5,null,'seller');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (22,3806088548,'Denise','Denesik','denise.denesik36','U2FsdGVkX1+lsprAkdN4y5Eht6itL33pcQGzW7MlYjm94KqsRfj1WQhOMShjz0uG','denisedenesik86@yahoo.com','(894) 099-6667 x03313','78083976997','https://s3.amazonaws.com/uifaces/faces/twitter/elbuscainfo/128.jpg',549163.8964,'14559 Kirlin Street',to_date('10-MAY-17','DD-MON-RR'),1,null,'seller');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (25,7197234958,'Clifton','Crona','clifton.crona','U2FsdGVkX1+ZNDsDotVLb1KTJnywBEhvUkJD/Z10EDU=','clifton.crona94@yahoo.com','(433) 194-0871 x4861','5903046007814','https://s3.amazonaws.com/uifaces/faces/twitter/lu4sh1i/128.jpg',455079.4059,'893 Sadie Wells Suite 395',to_date('15-JAN-18','DD-MON-RR'),5,null,'assistant');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (26,7537427069,'Michelle','Bailey','michelle_bailey','U2FsdGVkX19wXgI0al7dH0nJ1xReAU3N1NhSuJq7jFmZdgRF/1qCSFxpjI8RMSDd','michelle.bailey@gmail.com','1-288-074-3395','8360222533063','https://s3.amazonaws.com/uifaces/faces/twitter/rtyukmaev/128.jpg',302220.0198,'81744 Bosco Ford',to_date('18-MAY-17','DD-MON-RR'),5,null,'driver');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (28,3405489207,'Angelo','Walter','angelo.walter42','U2FsdGVkX19JT/2c0VlWTBpbUxfDJ3LX62x16EoGhmQ/a5yofwSXxVJS3AyH6R2l','angelo.walter52@hotmail.com','1-046-496-3875','6192453929152','https://s3.amazonaws.com/uifaces/faces/twitter/ivanfilipovbg/128.jpg',696476.5158,'84508 Terry Skyway',to_date('05-APR-18','DD-MON-RR'),4,null,'assistant');
Insert into EMPLOYEE (ID,SSN,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,TEL,BANK_ACCOUNT,PHOTO_URL,SALARY,ADDRESS,JOIN_DATE,SUPERVISOR_ID,DEPARTMENT_ID,ROLE) values (29,3717261769,'Myra','Kuhic','myra_kuhic','U2FsdGVkX1+T59E+ldGunUqu+2HgLaqVPDDkKhQIHHE=','myra91@yahoo.com','1-405-081-5060 x9706','7282495393035','https://s3.amazonaws.com/uifaces/faces/twitter/kijanmaharjan/128.jpg',993225.1041,'457 Predovic Cliff',to_date('08-OCT-17','DD-MON-RR'),1,null,'worker');
REM INSERTING into FOOD
SET DEFINE OFF;
REM INSERTING into FOOD_SHOP
SET DEFINE OFF;
REM INSERTING into HISTORY_ON_TRIP
SET DEFINE OFF;
REM INSERTING into LOCATION
SET DEFINE OFF;
REM INSERTING into MANAGER
SET DEFINE OFF;
Insert into MANAGER (ID,START_DATE) values (1,to_date('21-AUG-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (2,to_date('09-OCT-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (3,to_date('11-JUN-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (4,to_date('15-JUN-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (5,to_date('07-MAY-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (6,to_date('03-JUN-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (7,to_date('17-JUL-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (8,to_date('15-SEP-17','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (9,to_date('17-FEB-18','DD-MON-RR'));
Insert into MANAGER (ID,START_DATE) values (10,to_date('05-DEC-17','DD-MON-RR'));
REM INSERTING into OFFICE
SET DEFINE OFF;
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (3,'O''Keefe Group','7263 Eichmann Stream Suite 000',null,null,'849.196.7087 x8565',85.6249,27.2951);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (4,'Wilkinson, Willms and Stehr Inc.','836 Erdman Plaza Apt. 560',null,null,'(917) 680-7014 x8563',43.656,-124.3594);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (5,'Fahey Inc.','64263 Jeffery Divide',null,null,'043-909-0318',9.0709,-134.2279);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (1,'McClure Ltd.','6215 Dominic Isle Apt. 962',1,null,'1-343-763-5601',-76.7755,14.9179);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (2,'Rolfson-Pollich Inc.','171 Russel Fall',null,null,'1-478-307-9234 x46976',32.2743,-16.691);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (6,'Auer, Bahringer and Turner Inc.','09636 Ivan Curve Apt. 528',null,null,'483-030-9653',19.3489,133.2337);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (10,'Tillman, Lowe and Flatley Corp.','214 Eduardo Club',null,null,'783.965.7803 x790',-0.5077,-59.0956);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (8,'Moen-Nienow Ltd.','29264 Considine Forks',null,null,'360.783.2561 x9868',-49.5147,-0.2212);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (9,'Balistreri, Bosco and Haley Corp.','192 Earnest Vista Apt. 710',null,null,'1-472-810-1799',-86.0803,-105.7325);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (7,'Carter-Medhurst LLC','51361 Brown Islands',null,null,'(151) 379-1144',-66.1838,71.1349);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (11,'Yundt Group','506 Carolyn Wall',null,null,'751-717-0001 x620',-14.8726,-4.3459);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (12,'Hagenes Inc.','4291 Hugo Pines Suite 347',null,null,'(049) 456-6883',-63.8988,161.4131);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (13,'Schmeler, Gerlach and Tromp Group','379 Casey Field',null,null,'055.326.1820',-79.6787,37.8766);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (14,'White Group','44202 Oberbrunner Place',null,null,'(740) 227-6300',-59.6085,116.0939);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (15,'Kling-Jerde Ltd.','160 Braun Route Suite 924',null,null,'228-587-5679',-35.1708,92.8219);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (16,'Howell Group','6635 Beatrice Avenue',null,null,'401.329.5920',-40.9121,-75.316);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (17,'Lubowitz-Gislason Ltd.','514 Bernier Expressway',null,null,'270-330-0263',-36.0363,15.0216);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (18,'Mitchell Corp.','1669 Lakin Park Apt. 879',null,null,'1-385-368-4299 x24755',77.2878,-171.1099);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (19,'Nicolas-Nolan Corp.','088 Koepp Ferry',null,null,'609-788-9335',2.5962,31.205);
Insert into OFFICE (ID,NAME,ADDRESS,IS_HEADQUATER,DISTRICT_ID,HOTLINE,LATITUDE,LONGITUDE) values (20,'Toy-Collins Corp.','17102 Barrows Route Suite 349',null,null,'(095) 220-2147',-69.9562,40.5231);
REM INSERTING into PROMOTION
SET DEFINE OFF;
REM INSERTING into PROMOTION_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into REPAIR_EVENT
SET DEFINE OFF;
REM INSERTING into REPAIR_STATION
SET DEFINE OFF;
REM INSERTING into ROUTER_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into SELLER
SET DEFINE OFF;
REM INSERTING into SURCHARGE
SET DEFINE OFF;
REM INSERTING into SURCHARGE_TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into TICKET
SET DEFINE OFF;
REM INSERTING into TRANSACTION
SET DEFINE OFF;
REM INSERTING into TRIP
SET DEFINE OFF;
REM INSERTING into TRIP_DAILY
SET DEFINE OFF;
REM INSERTING into WARRANTY
SET DEFINE OFF;
REM INSERTING into WORKER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CHARGE_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHARGE_STATION_PK" ON "CHARGE_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OFFICE_PK" ON "OFFICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DRIVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVER_PK" ON "DRIVER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "WORKER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEPARTMENT_PK" ON "DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_UK" ON "EMPLOYEE" ("USERNAME", "SSN", "EMAIL", "BANK_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOCATION_PK" ON "LOCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROUTER_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUTER_TRIP_DAILY_PK" ON "ROUTER_TRIP_DAILY" ("LOCATION_ID", "TRIP_DAILY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER_PK" ON "MANAGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_PK" ON "CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRIP_DAILY_PK" ON "TRIP_DAILY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_TYPE_PK" ON "BUS_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROMOTION_TRIP_DAILY_PK" ON "PROMOTION_TRIP_DAILY" ("TRIP_DAILY_ID", "PROMOTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_PK" ON "BUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROMOTION_PK" ON "PROMOTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSISTANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT_PK" ON "ASSISTANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURCHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SURCHARGE_PK" ON "SURCHARGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DRIVER_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVER_UK" ON "DRIVER" ("LICENSE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index WARRANTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WARRANTY_PK" ON "WARRANTY" ("REPAIR_STATION_ID", "BUS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACTION_PK" ON "TRANSACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_PK" ON "EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TICKET_PK" ON "TICKET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPAIR_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPAIR_STATION_PK" ON "REPAIR_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUS_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUS_STATION_PK" ON "BUS_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORY_ON_TRIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORY_ON_TRIP_PK" ON "HISTORY_ON_TRIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_SHOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD_SHOP_PK" ON "FOOD_SHOP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_PK" ON "ACCOUNT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENT_PK" ON "REPAIR_EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISTRICT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISTRICT_PK" ON "DISTRICT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRIP_PK" ON "TRIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SELLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELLER_PK" ON "SELLER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURCHARGE_TRIP_DAILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SURCHARGE_TRIP_DAILY_PK" ON "SURCHARGE_TRIP_DAILY" ("TRIP_DAILY_ID", "SURCHARGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD_PK" ON "FOOD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY_PK" ON "CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ACCOUNT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNT" MODIFY ("OWNER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOOD_SHOP
--------------------------------------------------------

  ALTER TABLE "FOOD_SHOP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FOOD_SHOP" ADD CONSTRAINT "FOOD_SHOP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEPARTMENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "DEPARTMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "BUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUS" MODIFY ("REGISTRATION" NOT NULL ENABLE);
  ALTER TABLE "BUS" ADD CONSTRAINT "BUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUS_TYPE
--------------------------------------------------------

  ALTER TABLE "BUS_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUS_TYPE" MODIFY ("BRAND" NOT NULL ENABLE);
  ALTER TABLE "BUS_TYPE" ADD CONSTRAINT "BUS_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SURCHARGE
--------------------------------------------------------

  ALTER TABLE "SURCHARGE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SURCHARGE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SURCHARGE" ADD CONSTRAINT "SURCHARGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOCATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_UK" UNIQUE ("LICENSE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORY_ON_TRIP
--------------------------------------------------------

  ALTER TABLE "HISTORY_ON_TRIP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HISTORY_ON_TRIP" ADD CONSTRAINT "HISTORY_ON_TRIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTION" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTION" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TICKET" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TICKET" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TICKET" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TICKET" MODIFY ("TRIP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS_STATION
--------------------------------------------------------

  ALTER TABLE "BUS_STATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUS_STATION" ADD CONSTRAINT "BUS_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "PROMOTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROMOTION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROMOTION" ADD CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRIP_DAILY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "FOOD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FOOD" ADD CONSTRAINT "FOOD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRIP
--------------------------------------------------------

  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRIP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHARGE_STATION
--------------------------------------------------------

  ALTER TABLE "CHARGE_STATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CHARGE_STATION" ADD CONSTRAINT "CHARGE_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_UK_ID" UNIQUE ("USERNAME", "SSN", "EMAIL", "BANK_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "OFFICE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OFFICE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "OFFICE" ADD CONSTRAINT "OFFICE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPAIR_EVENT
--------------------------------------------------------

  ALTER TABLE "REPAIR_EVENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISTRICT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DISTRICT" ADD CONSTRAINT "DISTRICT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SELLER" ADD CONSTRAINT "SELLER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKER
--------------------------------------------------------

  ALTER TABLE "WORKER" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WORKER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "PROMOTION_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROMOTION_TRIP_DAILY" MODIFY ("PROMOTION_ID" NOT NULL ENABLE);
  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_PK" PRIMARY KEY ("TRIP_DAILY_ID", "PROMOTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WARRANTY
--------------------------------------------------------

  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_PK" PRIMARY KEY ("REPAIR_STATION_ID", "BUS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WARRANTY" MODIFY ("REPAIR_STATION_ID" NOT NULL ENABLE);
  ALTER TABLE "WARRANTY" MODIFY ("BUS_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "SURCHARGE_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
  ALTER TABLE "SURCHARGE_TRIP_DAILY" MODIFY ("SURCHARGE_ID" NOT NULL ENABLE);
  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_PK" PRIMARY KEY ("TRIP_DAILY_ID", "SURCHARGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "ASSISTANT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT" ADD CONSTRAINT "ASSISTANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "ROUTER_TRIP_DAILY" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
  ALTER TABLE "ROUTER_TRIP_DAILY" MODIFY ("TRIP_DAILY_ID" NOT NULL ENABLE);
  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_PK" PRIMARY KEY ("LOCATION_ID", "TRIP_DAILY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "MANAGER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPAIR_STATION
--------------------------------------------------------

  ALTER TABLE "REPAIR_STATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REPAIR_STATION" ADD CONSTRAINT "REPAIR_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK_OWNER" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "ASSISTANT" ADD CONSTRAINT "ASSISTANT_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "BUS" ADD CONSTRAINT "BUS_FK_TYPE" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUS_STATION
--------------------------------------------------------

  ALTER TABLE "BUS_STATION" ADD CONSTRAINT "BUS_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHARGE_STATION
--------------------------------------------------------

  ALTER TABLE "CHARGE_STATION" ADD CONSTRAINT "CHARGE_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CITY" ADD CONSTRAINT "CITY_FK_CENTER" FOREIGN KEY ("CENTER_DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_MANAGER" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "MANAGER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_OFFICE" FOREIGN KEY ("OFFICE_ID")
	  REFERENCES "OFFICE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" ADD CONSTRAINT "DISTRICT_FK_CITY" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CITY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" ADD CONSTRAINT "DRIVER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK_DEPART" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK_SUPERVISOR" FOREIGN KEY ("SUPERVISOR_ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "FOOD" ADD CONSTRAINT "FOOD_FK" FOREIGN KEY ("FOOD_SHOP_ID")
	  REFERENCES "FOOD_SHOP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOOD_SHOP
--------------------------------------------------------

  ALTER TABLE "FOOD_SHOP" ADD CONSTRAINT "FOOD_SHOP_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORY_ON_TRIP
--------------------------------------------------------

  ALTER TABLE "HISTORY_ON_TRIP" ADD CONSTRAINT "HISTORY_ON_TRIP_FK_TRIP" FOREIGN KEY ("TRIP_ID")
	  REFERENCES "TRIP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "OFFICE" ADD CONSTRAINT "OFFICE_FK_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_FK_PRO" FOREIGN KEY ("PROMOTION_ID")
	  REFERENCES "PROMOTION" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "PROMOTION_TRIP_DAILY" ADD CONSTRAINT "PROMOTION_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_EVENT
--------------------------------------------------------

  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK1" FOREIGN KEY ("ASSISTANCE_ID")
	  REFERENCES "ASSISTANT" ("ID") ENABLE;
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_BUS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "BUS" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_CREATOR" FOREIGN KEY ("CREATOR_ID")
	  REFERENCES "MANAGER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "DRIVER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "REPAIR_EVENT" ADD CONSTRAINT "REPAIR_EVENT_FK_STATION" FOREIGN KEY ("REPAIR_STATION_ID")
	  REFERENCES "REPAIR_STATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_STATION
--------------------------------------------------------

  ALTER TABLE "REPAIR_STATION" ADD CONSTRAINT "REPAIR_STATION_FK" FOREIGN KEY ("ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROUTER_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_FK_LOC" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "LOCATION" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ROUTER_TRIP_DAILY" ADD CONSTRAINT "ROUTER_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" ADD CONSTRAINT "SELLER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURCHARGE_TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_FK_SUR" FOREIGN KEY ("SURCHARGE_ID")
	  REFERENCES "SURCHARGE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SURCHARGE_TRIP_DAILY" ADD CONSTRAINT "SURCHARGE_TRIP_DAILY_FK_TRIP" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_FK_TRANSACTION" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANSACTION" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_FK_TRIP" FOREIGN KEY ("TRIP_ID")
	  REFERENCES "TRIP" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_ACCOUNT" FOREIGN KEY ("ACCOUNT")
	  REFERENCES "ACCOUNT" ("EMAIL") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK_SELLER" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "SELLER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIP
--------------------------------------------------------

  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_ASSISTANT" FOREIGN KEY ("ASSISTANT_ID")
	  REFERENCES "ASSISTANT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_BUS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "BUS" ("ID") ENABLE;
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_DAILY" FOREIGN KEY ("TRIP_DAILY_ID")
	  REFERENCES "TRIP_DAILY" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TRIP" ADD CONSTRAINT "TRIP_FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "DRIVER" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIP_DAILY
--------------------------------------------------------

  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_AR_ID" FOREIGN KEY ("ARRIVE_STATION_ID")
	  REFERENCES "BUS_STATION" ("ID") ENABLE;
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_BUS_TYPE" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TRIP_DAILY" ADD CONSTRAINT "TRIP_DAILY_FK_DE_ID" FOREIGN KEY ("DEPART_STATION_ID")
	  REFERENCES "BUS_STATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WARRANTY
--------------------------------------------------------

  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_FK_BUS" FOREIGN KEY ("BUS_TYPE_ID")
	  REFERENCES "BUS_TYPE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "WARRANTY" ADD CONSTRAINT "WARRANTY_FK_STATION" FOREIGN KEY ("REPAIR_STATION_ID")
	  REFERENCES "REPAIR_STATION" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKER
--------------------------------------------------------

  ALTER TABLE "WORKER" ADD CONSTRAINT "WORKER_FK" FOREIGN KEY ("ID")
	  REFERENCES "EMPLOYEE" ("ID") ON DELETE SET NULL ENABLE;
